// Additional questions for mixed quizzes — brings each from 20 to 50 questions.
// Distribution: mixed-1/2 heavy on early topics (01-07), mixed-3 balanced,
// mixed-4/5 heavy on later topics (08-10).

const MIXED_EXTRA = {

  "mixed-1": [
    // ── Early topics (01-07) ─────────────────────────────────────
    {
      q: "What does `man ls` open?",
      options: ["A file manager", "The manual (man page) for the ls command", "A list of all man pages", "The source code of ls"],
      answer: 1,
      explain: "`man` opens the manual page for any command. Navigate with arrow keys, search with `/term`, quit with `q`. `man 5 passwd` opens section 5 (file formats) for passwd.",
    },
    {
      q: "What does `ls -a` show that `ls` alone does not?",
      options: ["File permissions", "Hidden files and directories (names starting with `.`)", "File sizes", "Symbolic links"],
      answer: 1,
      explain: "Files starting with `.` are hidden in Linux. `ls -a` shows them. `ls -A` shows hidden files but not `.` (current dir) and `..` (parent dir).",
    },
    {
      q: "What does `cd -` do?",
      options: ["Goes to the home directory", "Goes to the previous working directory", "Goes up one directory", "Lists the directory stack"],
      answer: 1,
      explain: "`cd -` switches to the directory you were in before your last `cd`. Very useful for toggling between two directories without typing full paths.",
    },
    {
      q: "What does `mkdir -p a/b/c` do differently from `mkdir a/b/c`?",
      options: ["Makes the directory read-only", "Creates all parent directories as needed — no error if they already exist", "Creates a/b/c with full permissions", "Makes a symbolic link"],
      answer: 1,
      explain: "Without `-p`, `mkdir a/b/c` fails if `a` or `a/b` don't exist. `-p` creates the entire path. Also silently succeeds if the directory already exists.",
    },
    {
      q: "What does `head -n 20 file.txt` do?",
      options: ["Shows the last 20 lines", "Shows the first 20 lines", "Shows lines around line 20", "Counts 20 occurrences"],
      answer: 1,
      explain: "`head` shows the beginning of a file. Default is 10 lines. `-n 20` overrides to 20. `tail -n 20` for the last 20. `tail -f file` follows a live log.",
    },
    {
      q: "What does `wc -l file.txt` count?",
      options: ["Word count", "Number of lines", "Number of characters", "Number of spaces"],
      answer: 1,
      explain: "`wc` = word count. `-l` = lines, `-w` = words, `-c` = bytes, `-m` = characters. `wc -l < file` counts without printing the filename.",
    },
    {
      q: "What does `grep -r 'TODO' ./src/` do?",
      options: ["Searches only src/ for TODO", "Recursively searches all files under src/ for lines containing TODO", "Replaces TODO in src/", "Creates a TODO list"],
      answer: 1,
      explain: "`-r` = recursive. Searches all files in the directory tree. Add `-l` to show only filenames. `-n` adds line numbers. `--include='*.py'` limits to Python files.",
    },
    {
      q: "What is the difference between `>` and `>>` redirection?",
      options: ["`>` appends; `>>` overwrites", "`>` overwrites the file; `>>` appends to it", "They are identical", "`>` is for stdout; `>>` is for stderr"],
      answer: 1,
      explain: "`command > file` truncates and overwrites. `command >> file` appends to the end. Use `>>` for log files and accumulating output.",
    },
    {
      q: "What does `passwd jahid` do when run as root?",
      options: ["Shows jahid's password hash", "Changes jahid's password without needing the old one", "Locks jahid's account", "Creates jahid's account"],
      answer: 1,
      explain: "Root can change any user's password without knowing the current one. A regular user running `passwd` (no argument) changes their own password and must provide the old one first.",
    },
    {
      q: "What does `id` command show?",
      options: ["System ID and hostname", "Current user's UID, GID, and all group memberships", "Process IDs", "Network interface IDs"],
      answer: 1,
      explain: "`id` shows: `uid=1000(jahid) gid=1000(jahid) groups=1000(jahid),27(sudo),1001(docker)`. Check group membership at a glance. `id username` shows another user's info.",
    },
    {
      q: "What does `ln -s /etc/nginx/nginx.conf nginx.conf` create?",
      options: ["A copy of nginx.conf", "A symbolic link called nginx.conf pointing to /etc/nginx/nginx.conf", "A hard link", "A backup"],
      answer: 1,
      explain: "`ln -s` creates a symbolic link. The link `nginx.conf` in the current directory points to the real file. Editing the link edits the real file. Useful for creating shortcuts.",
    },
    {
      q: "What command shows real-time CPU and memory usage in an interactive view?",
      options: ["ps aux", "top (or htop for a better UI)", "vmstat", "uptime"],
      answer: 1,
      explain: "`top` is the classic interactive process monitor. Press `q` to quit, `k` to kill a process, `M` to sort by memory, `P` to sort by CPU. `htop` is a friendlier version.",
    },
    {
      q: "What does `pkill -f 'python server.py'` do?",
      options: ["Lists python processes", "Sends SIGTERM to all processes whose full command line matches 'python server.py'", "Kills only the first matching process", "Freezes the matching process"],
      answer: 1,
      explain: "`pkill -f` matches against the full command string, not just the process name. More flexible than `kill PID` when you don't know the PID.",
    },
    {
      q: "What does `uptime` command show?",
      options: ["CPU uptime only", "How long the system has been running, number of users, and load averages", "Network uptime", "Disk uptime"],
      answer: 1,
      explain: "Example: `15:42:03 up 3 days, 2:15, 2 users, load average: 0.15, 0.10, 0.08`. The three load averages are 1-minute, 5-minute, 15-minute. High values indicate CPU pressure.",
    },
    {
      q: "What does `ss -tulnp` show?",
      options: ["SSH tunnels", "TCP and UDP listening ports with process names and PIDs", "System socket statistics", "TCP upload/download stats"],
      answer: 1,
      explain: "`-t` TCP, `-u` UDP, `-l` listening only, `-n` numeric (no DNS), `-p` processes. The go-to command for seeing what's listening on which ports.",
    },
    {
      q: "What does `chmod 644 file.txt` set?",
      options: ["rwxr-xr-x", "rw-r--r-- (owner read+write, group read, others read)", "rw-rw-r--", "rwx------"],
      answer: 1,
      explain: "644 = 6(rw-) for owner, 4(r--) for group, 4(r--) for others. The standard permission for text files, config files, and web content.",
    },
    {
      q: "What does `find /home -name '*.sh' -executable` find?",
      options: ["All .sh files", "Shell scripts under /home that have the executable bit set", "sh files modified recently", "sh files owned by root"],
      answer: 1,
      explain: "`-executable` is a `find` test that checks if the file can be executed by the current user. Combined with `-name '*.sh'`, it finds runnable shell scripts.",
    },
    {
      q: "What does `usermod -aG docker jahid` do?",
      options: ["Removes jahid from docker group", "Appends jahid to the docker group without removing existing group memberships", "Creates the docker group", "Changes jahid's primary group to docker"],
      answer: 1,
      explain: "The `-a` (append) flag is critical — without it, `-G docker` would REPLACE all of jahid's groups with just docker. Always use `-aG` when adding to a supplementary group.",
    },
    {
      q: "What does `ip addr show eth0` display?",
      options: ["Ethernet hardware specs", "IP addresses, subnet, and state of the eth0 interface", "Routing table for eth0", "MAC address only"],
      answer: 1,
      explain: "Shows the interface's MAC address, IPv4 (inet) and IPv6 (inet6) addresses with prefix length, and link state (UP/DOWN). Replaces the older `ifconfig eth0`.",
    },
    {
      q: "What does `apt-get autoremove` do?",
      options: ["Removes all packages", "Removes packages that were installed as dependencies but are no longer needed", "Automatically removes old kernels only", "Removes apt itself"],
      answer: 1,
      explain: "When you uninstall a package, its dependencies stay behind. `autoremove` cleans up those orphaned packages. Safe to run periodically to reclaim disk space.",
    },
    {
      q: "What does `du -sh /var/log/` show?",
      options: ["Files in /var/log", "The total disk usage of /var/log/ in human-readable format", "Last access time of /var/log/", "The number of log files"],
      answer: 1,
      explain: "`du -sh` = summarise (`-s`) in human-readable (`-h`) format. Without `-s` it shows size for every subdirectory. `du -sh */ | sort -h` ranks directories by size.",
    },
    {
      q: "What does `uname -r` show?",
      options: ["Hostname", "The kernel release version (e.g. 6.5.0-45-generic)", "Architecture", "Uptime"],
      answer: 1,
      explain: "`uname -r` = kernel release. `uname -a` shows everything: kernel name, hostname, release, version, machine, OS. Useful when debugging kernel-specific issues.",
    },
    {
      q: "What does `dmesg | grep -i error` show?",
      options: ["Disk errors only", "Kernel ring buffer messages containing the word 'error' (case-insensitive)", "Application errors", "System log errors"],
      answer: 1,
      explain: "`dmesg` = kernel messages. `-i` makes grep case-insensitive. This is the first command to run after a hardware issue, driver failure, or mysterious crash.",
    },
    // ── Later topics (08-10) ─────────────────────────────────────
    {
      q: "What does `$#` contain in a bash script?",
      options: ["The script's PID", "The number of positional arguments passed to the script", "The last exit code", "The script's name"],
      answer: 1,
      explain: "`$#` = argument count. If you call `./script.sh a b c`, then `$#` is 3. Use it to validate that the right number of arguments were provided.",
    },
    {
      q: "What does `ssh-copy-id user@host` do?",
      options: ["Copies the host's key locally", "Copies your public key to host's ~/.ssh/authorized_keys — enabling key-based login", "Creates a new SSH key pair", "Tests SSH connectivity"],
      answer: 1,
      explain: "`ssh-copy-id` appends your `~/.ssh/id_*.pub` to the remote `~/.ssh/authorized_keys`. After this, you can log in without a password (using your private key instead).",
    },
    {
      q: "What does `free -h` display?",
      options: ["Free disk space in human-readable format", "RAM and swap usage in human-readable format", "Free inodes", "Free process slots"],
      answer: 1,
      explain: "`free` shows total, used, and free memory for RAM and swap. `-h` makes it human-readable. The 'available' column is more useful than 'free' — it includes reclaimable cache.",
    },
    {
      q: "What is a here-document (`<<EOF ... EOF`) used for in bash?",
      options: ["Reading from a file named EOF", "Providing multi-line text as stdin to a command, inline in the script", "Commenting out multiple lines", "Creating a file named EOF"],
      answer: 1,
      explain: "Here-docs let you write multi-line strings inline: `cat <<EOF\\nline1\\nline2\\nEOF`. Used with ssh for remote commands, with mysql for queries, or any command needing multi-line input.",
    },
    {
      q: "What does `top` show in the 'load average' line?",
      options: ["CPU temperature", "Average number of processes waiting to run over 1, 5, and 15 minute windows", "Memory load", "Network load"],
      answer: 1,
      explain: "Load average = runnable processes + uninterruptible sleeping. On a 4-core system, load 4.0 = fully loaded. Load > CPU count means queuing. 15-min average smooths spikes.",
    },
    {
      q: "What does `PermitRootLogin no` in sshd_config do?",
      options: ["Prevents root from using sudo", "Blocks direct SSH login as root — you must SSH as a regular user then sudo", "Disables root account", "Requires password for root"],
      answer: 1,
      explain: "Direct root SSH login is a major security risk. Best practice: `PermitRootLogin no`, then SSH as your user and `sudo` for admin tasks. Limits brute-force target.",
    },
    {
      q: "What does `for f in $(find . -name '*.log'); do gzip \"$f\"; done` do?",
      options: ["Lists all .log files", "Compresses every .log file found in the current directory tree", "Deletes log files after compressing", "Creates a single archive of all logs"],
      answer: 1,
      explain: "Combines `find` with a loop. Each found file is gzipped in place, creating `file.log.gz`. Note: filenames with spaces would break — `find ... -exec gzip {} \\;` is safer.",
    },
  ],

  "mixed-2": [
    // ── Early topics (01-07) ─────────────────────────────────────
    {
      q: "What does `cat /proc/cpuinfo` show?",
      options: ["CPU temperature", "Detailed information about each CPU core: model, speed, cache, features", "CPU usage percentage", "Which processes use the CPU"],
      answer: 1,
      explain: "`/proc/cpuinfo` is a virtual file exposing kernel data. Count cores: `grep -c 'processor' /proc/cpuinfo`. See CPU model: `grep 'model name' /proc/cpuinfo | head -1`.",
    },
    {
      q: "What does `echo $?` show after a command?",
      options: ["The command's PID", "The exit code of the last command (0 = success, non-zero = error)", "The question mark variable", "The command's output"],
      answer: 1,
      explain: "Every command exits with a code. 0 = success. Any other value = failure. `$?` holds it. Must check immediately — the next command overwrites it.",
    },
    {
      q: "What does `tar -xzf archive.tar.gz -C /tmp/` do?",
      options: ["Creates a tar.gz in /tmp/", "Extracts the archive into /tmp/ directory", "Lists the archive contents", "Compresses /tmp/"],
      answer: 1,
      explain: "`-x` = extract, `-z` = gunzip, `-f` = file, `-C` = change to directory before extracting. Without `-C`, files extract into the current directory.",
    },
    {
      q: "What does `awk '{print $2}' file.txt` do?",
      options: ["Prints the second file", "Prints the second whitespace-delimited field from each line", "Skips 2 lines then prints", "Prints 2 copies of the file"],
      answer: 1,
      explain: "`awk` splits each line on whitespace. `$1` = first field, `$2` = second, `$NF` = last. `awk -F: '{print $1}' /etc/passwd` uses `:` as delimiter to print usernames.",
    },
    {
      q: "What does `sort -u file.txt` do?",
      options: ["Sorts in reverse", "Sorts the file and removes duplicate lines", "Sorts by modification time", "Sorts uppercase first"],
      answer: 1,
      explain: "`-u` = unique (remove duplicates after sorting). `sort -n` sorts numerically. `sort -k2` sorts by second column. `sort -rn` sorts numerically in reverse.",
    },
    {
      q: "What does `chmod u+s /usr/bin/myapp` do?",
      options: ["Sets the sticky bit", "Sets the SUID bit — myapp runs with the file owner's privileges regardless of who calls it", "Adds the group sticky bit", "Makes myapp system-wide"],
      answer: 1,
      explain: "`u+s` adds SUID. When any user runs myapp, it runs as the owner of /usr/bin/myapp (usually root). Classic example: `/usr/bin/passwd` is SUID root so users can change their own password.",
    },
    {
      q: "What does `lscpu` display?",
      options: ["CPU processes", "Architecture, sockets, cores, threads, and CPU features from the system's perspective", "Last CPU error", "CPU command list"],
      answer: 1,
      explain: "`lscpu` summarises the CPU topology and capabilities. Useful for knowing total threads, cache sizes, virtualisation support (VT-x/AMD-V), and which ISA extensions are available.",
    },
    {
      q: "What does `netstat -an | grep LISTEN` show?",
      options: ["All network connections", "Only sockets currently in the LISTEN state (services waiting for connections)", "Listening interfaces only", "Network errors"],
      answer: 1,
      explain: "LISTEN state means the port is bound and waiting. This lets you verify services are running. `ss -tlnp` is the modern replacement — same info, faster.",
    },
    {
      q: "What does `sudo systemctl restart nginx` do?",
      options: ["Stops nginx", "Stops then immediately starts nginx — applying config changes", "Reloads nginx config without restarting", "Installs nginx"],
      answer: 1,
      explain: "`restart` = stop + start. Drops all active connections. Use `reload` (sends HUP) when you only need to reload the config — it's zero-downtime for nginx.",
    },
    {
      q: "What is `/etc/fstab` used for?",
      options: ["File system table — defines filesystems and mount points that are mounted automatically at boot", "A list of forbidden file types", "Fast access tab for the shell", "File status backup table"],
      answer: 0,
      explain: "Each line: `device mountpoint fstype options dump pass`. Edit it to add persistent mounts (NFS shares, extra disks). Always `mount -a` to test before rebooting.",
    },
    {
      q: "What does `traceroute google.com` show?",
      options: ["Google's server config", "Each network hop between your machine and google.com, with round-trip times", "DNS resolution path", "HTTP request path"],
      answer: 1,
      explain: "`traceroute` sends packets with increasing TTL to reveal each router hop. Useful for diagnosing where packet loss or latency occurs. `mtr` combines traceroute and ping.",
    },
    {
      q: "What does `cat /proc/meminfo | grep MemAvailable` show?",
      options: ["Total RAM", "How much memory is available for new processes (includes reclaimable caches)", "Swap available", "Memory in use"],
      answer: 1,
      explain: "`MemAvailable` is the key metric — more accurate than `MemFree`. Linux uses free memory for caching; `MemAvailable` accounts for cache that can be freed if needed.",
    },
    {
      q: "What does `useradd -m -s /bin/bash newuser` do?",
      options: ["Creates a user without a home directory", "Creates a user with a home directory and bash as the login shell", "Creates a system user", "Creates a user with no password"],
      answer: 1,
      explain: "`-m` = create home directory. `-s /bin/bash` = set login shell. Without `-m`, no home directory is created. Without `-s`, the system default shell is used (often /bin/sh).",
    },
    {
      q: "What does `grep -c '' file.txt` count?",
      options: ["Empty lines", "Every line (the empty pattern matches all lines)", "Characters", "Words"],
      answer: 1,
      explain: "`grep -c ''` matches every line because every line contains the empty string. It's a fast, POSIX-compatible alternative to `wc -l` for counting lines.",
    },
    {
      q: "What does `ip route show` display?",
      options: ["HTTP routes", "The kernel's routing table — showing how packets are sent to different destinations", "Open network connections", "DNS routes"],
      answer: 1,
      explain: "The routing table determines which interface and gateway to use for each destination. `default via 192.168.1.1 dev eth0` means all non-matched traffic goes via that gateway.",
    },
    {
      q: "What does `/proc/loadavg` contain?",
      options: ["Average disk load", "Load averages at 1, 5, 15 minutes, running/total processes, and last PID used", "Average CPU temperature", "Log of loading times"],
      answer: 1,
      explain: "`cat /proc/loadavg` shows e.g. `0.15 0.20 0.18 1/312 5678` — the 1/312 means 1 process running out of 312 total. This is where `uptime` and `top` get their data.",
    },
    {
      q: "What does `crontab -l` do?",
      options: ["Lists all users' crontabs", "Lists the current user's scheduled cron jobs", "Logs the last cron runs", "Links crontab to a file"],
      answer: 1,
      explain: "`crontab -l` shows your personal crontab. To see root's: `sudo crontab -l`. System-wide cron jobs are in `/etc/cron.d/`, `/etc/cron.daily/`, etc.",
    },
    {
      q: "What does `fdisk -l` show?",
      options: ["Files and directories", "All disk partitions on the system", "Failed disk sectors", "File descriptor limits"],
      answer: 1,
      explain: "`sudo fdisk -l` lists all disks and their partitions with sizes, types, and start/end sectors. `lsblk` is a cleaner alternative that shows block device tree.",
    },
    {
      q: "What does `rsync -avz src/ user@host:/dest/` do?",
      options: ["Copies files and deletes the source", "Syncs src/ to a remote destination with archive mode, verbose, and compression", "Only shows differences", "Zips src/ then copies"],
      answer: 1,
      explain: "`-a` = archive (preserves permissions, timestamps, symlinks). `-v` = verbose. `-z` = compress in transit. Rsync only transfers changed parts of files — very efficient for large syncs.",
    },
    {
      q: "What does `cut -d, -f2,4 data.csv` do?",
      options: ["Cuts 2 and 4 characters", "Extracts the 2nd and 4th comma-delimited fields from each line", "Cuts after 2nd line, 4 times", "Removes fields 2 and 4"],
      answer: 1,
      explain: "`-d,` sets comma as delimiter. `-f2,4` selects fields 2 and 4. Use `-f2-4` for a range. Useful for quickly extracting columns from CSV or delimited files.",
    },
    // ── Later topics (08-10) ─────────────────────────────────────
    {
      q: "In a bash script, what does `exit 1` do?",
      options: ["Goes to line 1", "Terminates the script with exit code 1 (failure)", "Exits the current function", "Exits after 1 second"],
      answer: 1,
      explain: "`exit N` terminates the script with code N. 0 = success. 1-255 = various failure codes. The caller can check `$?`. `exit` alone uses the last command's exit code.",
    },
    {
      q: "What does `journalctl -f` do?",
      options: ["Searches journal for 'f'", "Follows the journal log in real-time (like `tail -f` for systemd logs)", "Shows only failed units", "Formats journal output"],
      answer: 1,
      explain: "`journalctl -f` streams new log entries as they appear. Equivalent to `tail -f /var/log/syslog` but for systemd's journal. Ctrl+C to stop.",
    },
    {
      q: "What does `[[ $str =~ ^[0-9]+$ ]]` check in bash?",
      options: ["Whether $str starts with 0", "Whether $str matches the regex — i.e. consists entirely of digits (is a positive integer)", "Whether $str equals '^[0-9]+$'", "Whether $str contains any number"],
      answer: 1,
      explain: "`=~` inside `[[ ]]` does regex matching. `^[0-9]+$` = start, one-or-more digits, end. Returns true only for strings like `0`, `42`, `100`. The match result is in `${BASH_REMATCH[@]}`.",
    },
    {
      q: "What does `local VAR=value` inside a bash function do?",
      options: ["Creates a system-wide variable", "Creates a variable scoped to the function — invisible outside it", "Makes VAR read-only", "Creates a variable in /tmp/"],
      answer: 1,
      explain: "Without `local`, variables set in a function are global. `local` limits the variable to the function's scope. Essential for avoiding name collisions in reusable functions.",
    },
    {
      q: "What does `authorized_keys` contain on an SSH server?",
      options: ["Server's private keys", "Public keys of clients allowed to log in without a password", "Encrypted passwords", "Server certificates"],
      answer: 1,
      explain: "`~/.ssh/authorized_keys` holds one public key per line. When a client connects, the server checks if any key in this file matches the client's private key (challenge/response).",
    },
    {
      q: "What does `sar -r 1 5` show?",
      options: ["Process runs per second", "Memory usage statistics every 1 second for 5 intervals", "Disk read rates", "Routing changes"],
      answer: 1,
      explain: "`sar` (System Activity Reporter) is part of the sysstat package. `-r` = memory. It shows `kbmemfree`, `kbmemused`, `%memused` etc. at timed intervals.",
    },
    {
      q: "What does `set -e` do at the top of a bash script?",
      options: ["Enables extended globbing", "Makes the script exit immediately if any command returns a non-zero exit code", "Sets the editor variable", "Echoes every command"],
      answer: 1,
      explain: "`set -e` (errexit) is a safety net. Without it, a failing command is silently ignored and the script continues. With it, any error stops execution immediately.",
    },
    {
      q: "What does `while read -r line; do echo \"$line\"; done < file.txt` do?",
      options: ["Writes to file.txt", "Reads file.txt line by line and prints each line", "Reads user input", "Loops indefinitely"],
      answer: 1,
      explain: "Redirecting `< file.txt` at the end of the while loop feeds the file into `read`. `-r` prevents backslash interpretation. This is how you process file content line by line.",
    },
    {
      q: "What does `PubkeyAuthentication yes` in sshd_config enable?",
      options: ["Password authentication", "SSH login using public/private key pairs", "PAM authentication", "Kerberos"],
      answer: 1,
      explain: "This must be `yes` (the default) for key-based logins to work. If users complain their SSH keys are rejected, check both this setting and that `~/.ssh/authorized_keys` has correct permissions (600 or 644).",
    },
    {
      q: "What does `top` show when load average is greater than the CPU core count?",
      options: ["CPU is underutilised", "Processes are waiting for CPU time — the system is overloaded", "Memory is full", "Disk I/O is the bottleneck"],
      answer: 1,
      explain: "Load average represents the average number of runnable (or blocked) processes. If you have 4 cores and load is 6.0, there are 2 more processes wanting CPU than can run simultaneously.",
    },
  ],

  "mixed-3": [
    // ── Balanced: early (01-07) and later (08-10) ────────────────
    {
      q: "What does `xargs` do in `find . -name '*.tmp' | xargs rm`?",
      options: ["Removes only the first file", "Takes lines from stdin and passes them as arguments to `rm`", "Extends the rm command", "Previews what rm would delete"],
      answer: 1,
      explain: "`xargs` bridges commands that output filenames with commands that take filenames as arguments. `find ... | xargs rm` is more efficient than `find ... -exec rm {} \\;` for many files.",
    },
    {
      q: "What does `chmod 1777 /shared/` set?",
      options: ["Full permission for everyone", "Full permission for everyone plus the sticky bit — users can only delete their own files", "Sticky bit only", "SUID for the directory"],
      answer: 1,
      explain: "The leading `1` sets the sticky bit (also writable as `chmod +t`). Combined with 777, it makes a shared writable directory where users can't delete each other's files — exactly like `/tmp`.",
    },
    {
      q: "What does `ps aux --sort=-%cpu | head -6` do?",
      options: ["Lists 6 random processes", "Shows the top 5 CPU-consuming processes (plus the header line)", "Sorts by memory", "Shows processes of 6 users"],
      answer: 1,
      explain: "`--sort=-%cpu` = descending CPU sort (the `-` means descending). `head -6` = header + top 5 rows. A quick way to find the most CPU-hungry processes.",
    },
    {
      q: "What is the purpose of `~/.bashrc`?",
      options: ["Run commands at every shell exit", "Run commands when a new interactive non-login bash shell starts — aliases, functions, exports", "System-wide bash config", "Bash error recovery file"],
      answer: 1,
      explain: "`~/.bashrc` is sourced for interactive non-login shells (e.g. opening a terminal emulator). `~/.bash_profile` or `~/.profile` is for login shells. Put aliases and custom functions in `~/.bashrc`.",
    },
    {
      q: "What does `strace -p 1234` do?",
      options: ["Shows the process tree at PID 1234", "Traces all system calls made by the running process with PID 1234", "Stops process 1234", "Shows stack trace of 1234"],
      answer: 1,
      explain: "`strace` intercepts and records system calls. Useful for debugging: why is this process hanging? Which files is it opening? What errno is it getting? Can cause some overhead.",
    },
    {
      q: "What does `echo \"export PATH=$PATH:/opt/myapp/bin\" >> ~/.bashrc` do?",
      options: ["Temporarily adds to PATH", "Permanently adds /opt/myapp/bin to PATH for future bash sessions", "Removes the old PATH", "Overwrites ~/.bashrc"],
      answer: 1,
      explain: "`>>` appends the export line to `~/.bashrc`. New terminals pick it up. Run `source ~/.bashrc` to apply it to the current session without opening a new terminal.",
    },
    {
      q: "In bash, what does `${VAR:-default}` evaluate to?",
      options: ["The string 'default'", "$VAR if it's set and non-empty, otherwise the string 'default'", "Always 'default'", "An error if VAR is unset"],
      answer: 1,
      explain: "This is a parameter expansion with a default. `${VAR:-default}` = use VAR if set, else use 'default'. `${VAR:=default}` also assigns 'default' to VAR. Very useful in scripts.",
    },
    {
      q: "What does `sudo -i` do?",
      options: ["Interactive sudo prompt", "Opens a root login shell (sources root's profile and starts in root's home)", "Installs sudo", "Lists sudo history"],
      answer: 1,
      explain: "`sudo -i` = interactive login shell as root. `sudo -s` gives a non-login root shell. `sudo su -` achieves the same as `sudo -i`. The `-i` properly sets the environment for root.",
    },
    {
      q: "What does `nc -zv host 22` do?",
      options: ["Connects to host and starts a chat", "Tests if port 22 is open on host — zero-I/O mode, verbose output", "Downloads from port 22", "Scans all ports on host"],
      answer: 1,
      explain: "`nc` (netcat) with `-z` = port scan (no data). `-v` = verbose. Very useful for testing firewall rules: 'can this machine reach that port?' without needing SSH to actually work.",
    },
    {
      q: "What does `journalctl --disk-usage` show?",
      options: ["Disk usage of all filesystems", "The amount of disk space the systemd journal is consuming", "The largest journal entry", "Log file sizes in /var/log"],
      answer: 1,
      explain: "systemd journals can grow large. `--disk-usage` shows total space consumed. Manage retention with `journalctl --vacuum-time=30d` (keep last 30 days) or `--vacuum-size=500M`.",
    },
    {
      q: "What does `function greet() { echo \"Hello, $1\"; }` and then `greet Alice` print?",
      options: ["Hello, $1", "Hello, Alice", "greet Alice", "Error — wrong syntax"],
      answer: 1,
      explain: "Inside a function, `$1` is the first argument passed to THAT function (not the script). `greet Alice` sets `$1=Alice` inside the function scope. Functions have their own positional parameters.",
    },
    {
      q: "What does `getfacl file.txt` show?",
      options: ["File creation time", "All ACL entries: owning user, group, and any extra per-user/group ACL rules", "File access count", "Group ACL only"],
      answer: 1,
      explain: "`getfacl` (get file access control list) shows standard permissions plus any extra ACL entries. A `+` at the end of `ls -l` output indicates ACLs exist.",
    },
    {
      q: "What does `ssh -L 8080:internal-server:80 user@bastion` create?",
      options: ["Forwards port 80 on bastion to you", "A local tunnel: connections to localhost:8080 are forwarded through bastion to internal-server:80", "A remote tunnel", "A VPN connection"],
      answer: 1,
      explain: "Local port forwarding: `-L local_port:remote_host:remote_port`. You access `localhost:8080`, SSH tunnels it to `internal-server:80` via bastion. Used for reaching services behind firewalls.",
    },
    {
      q: "What does `pgrep -l nginx` do?",
      options: ["Kills nginx", "Lists PIDs and process names matching 'nginx'", "Counts nginx processes", "Shows nginx's parent process"],
      answer: 1,
      explain: "`pgrep` searches running processes by name. `-l` = list (show name + PID). `pgrep -c nginx` counts matches. `pgrep -x nginx` matches the exact name (not just a substring).",
    },
    {
      q: "What does `trap 'echo Caught SIGINT' INT` do in a script?",
      options: ["Ignores Ctrl+C", "Runs 'echo Caught SIGINT' when the script receives SIGINT (Ctrl+C) instead of immediately exiting", "Sends SIGINT to child processes", "Only traps the first Ctrl+C"],
      answer: 1,
      explain: "`trap` intercepts signals. Useful for cleanup: `trap 'rm -f /tmp/lock; exit' INT TERM EXIT` ensures cleanup happens even if the script is interrupted.",
    },
    {
      q: "What does `visudo` do compared to directly editing `/etc/sudoers`?",
      options: ["They are identical", "visudo validates syntax before saving — preventing a broken sudoers file that could lock you out", "visudo requires root's password", "visudo only works for the current user"],
      answer: 1,
      explain: "A broken `/etc/sudoers` disables ALL sudo access, potentially locking you out of the system. `visudo` checks syntax before closing and warns you if there's an error.",
    },
    {
      q: "What does `${!VAR}` do in bash (with the `!`)?",
      options: ["Negates the value of VAR", "Indirect expansion — uses the VALUE of VAR as a variable name and returns that variable's value", "Checks if VAR is unset", "Expands to VAR's length"],
      answer: 1,
      explain: "If `NAME='user'` and `user='jahid'`, then `${!NAME}` = `jahid`. Indirect expansion lets you dynamically choose which variable to expand. `${#VAR}` gives the string length.",
    },
    {
      q: "What does `ssh -R 9090:localhost:3000 user@server` create?",
      options: ["A local tunnel", "A reverse tunnel: connections to server:9090 are forwarded back to your localhost:3000", "Starts a proxy on port 3000", "Opens a shell on port 9090"],
      answer: 1,
      explain: "Reverse port forwarding: `-R remote_port:local_host:local_port`. Useful for exposing a service on your laptop through a public server. Requires `GatewayPorts yes` in sshd_config to be public.",
    },
    {
      q: "What does `uniq -c` do when processing sorted input?",
      options: ["Removes all duplicates", "Counts consecutive duplicate lines and prefixes each unique line with its count", "Keeps only unique lines without counting", "Removes unique lines"],
      answer: 1,
      explain: "`uniq -c` only compares adjacent lines — that's why input should be sorted first. `sort file | uniq -c | sort -rn` gives a frequency table, highest count first.",
    },
    {
      q: "What does `set -u` (or `set -o nounset`) do in bash?",
      options: ["Sets the user", "Treats unset variables as errors — the script exits if you reference an undefined variable", "Unlocks set variables", "Unsets all variables"],
      answer: 1,
      explain: "`set -u` catches typos in variable names. Without it, `$USRNAME` (typo for `$USERNAME`) silently expands to empty string. With `set -u`, the script errors and exits.",
    },
    {
      q: "What does `logwatch` tool do?",
      options: ["Watches log files in real-time", "Analyses system logs and sends a daily summary email to the admin", "Rotates logs", "Blocks access to log files"],
      answer: 1,
      explain: "Logwatch parses `/var/log/` files and generates a human-readable summary of notable events — failed logins, disk usage, service status. Often configured to email root daily.",
    },
    {
      q: "What does `mktemp` create?",
      options: ["A temporary user", "A unique temporary file (or directory with -d) safely in /tmp, returning the filename", "A template file", "A temporary mount point"],
      answer: 1,
      explain: "`TMPFILE=$(mktemp)` creates a unique file like `/tmp/tmp.k3Jd7P`. Use it instead of `FILE=/tmp/myfile` to avoid name collisions between concurrent script runs.",
    },
    {
      q: "What does `inode` exhaustion mean and how do you detect it?",
      options: ["Too many large files", "All inode slots are used up — can't create new files even with free disk space. Check with `df -i`", "Index nodes are corrupted", "Inodes are too fragmented"],
      answer: 1,
      explain: "Each file consumes one inode. Small-file workloads (e.g. mail servers, caches) can exhaust inodes while disk space remains. `df -i` shows inode usage. Solution: clean up small files or reformat with more inodes.",
    },
    {
      q: "What does `sudo tcpdump -i eth0 port 80 -w capture.pcap` do?",
      options: ["Blocks port 80 traffic", "Captures HTTP traffic on eth0 and saves it to a file for later analysis", "Shows port 80 statistics", "Forwards port 80 traffic"],
      answer: 1,
      explain: "`tcpdump` captures packets. `-i eth0` = interface, `port 80` = filter, `-w file` = write to pcap. Open the file in Wireshark for GUI analysis. Essential for network debugging.",
    },
    {
      q: "What does `bash -n script.sh` do?",
      options: ["Runs the script in a new terminal", "Syntax-checks the script without executing it", "Runs the script in no-interactive mode", "Names the script"],
      answer: 1,
      explain: "`-n` = noexec (don't execute, just parse). Catches syntax errors before running the script in production. Won't catch logic errors or runtime failures — just parsing issues.",
    },
    {
      q: "What does `find / -user root -perm -4000` find that's security-relevant?",
      options: ["All files owned by root", "SUID files owned by root — programs that run as root when any user executes them", "Root's configuration files", "Files root can't access"],
      answer: 1,
      explain: "SUID + root ownership = any user can run this program with root privileges. Legitimate examples: `/usr/bin/passwd`, `/usr/bin/sudo`. Unexpected SUID root files are a major red flag.",
    },
    {
      q: "What does `diff -r dir1/ dir2/` do?",
      options: ["Removes differences between directories", "Recursively compares files in two directories, showing what differs", "Merges the two directories", "Shows only files unique to each directory"],
      answer: 1,
      explain: "`diff -r` compares directory trees recursively. Shows line-by-line differences for files that exist in both, and notes files that exist in only one. Useful for comparing config directories.",
    },
    {
      q: "What does `array=( $(ls) )` do in bash?",
      options: ["Makes ls an array", "Creates an array where each element is a filename from the current directory", "Creates a literal array with $(ls)", "Errors if there are no files"],
      answer: 1,
      explain: "Word-splitting assigns each ls output word to an array element. BUT this breaks for filenames with spaces. Safer: `mapfile -t array < <(ls)` or use glob: `array=( * )`.",
    },
    {
      q: "What does `systemctl mask nginx` do and why is it stronger than `disable`?",
      options: ["Same as disable", "Creates a symlink to /dev/null — prevents the service from ever being started, even manually or as a dependency", "Masks the service name in output", "Sets the service to manual start"],
      answer: 1,
      explain: "`disable` only removes the boot symlink. `mask` symlinks the unit file to `/dev/null`, so `systemctl start nginx` also fails. Use `unmask` to reverse it.",
    },
    {
      q: "What does `ls /proc/1/fd/` show?",
      options: ["Files in root's home", "File descriptors (open files) of PID 1 (systemd/init)", "The first filesystem descriptor", "Files created on boot"],
      answer: 1,
      explain: "Every process has a `/proc/PID/fd/` directory containing symlinks to every file descriptor it has open. Useful for recovering deleted files that a process still has open.",
    },
    {
      q: "What does the `PIPESTATUS` array contain in bash?",
      options: ["PIDs of pipe stages", "Exit codes of all commands in the last pipeline", "Pipe buffer sizes", "Status of background pipes"],
      answer: 1,
      explain: "`cmd1 | cmd2 | cmd3`. After this, `${PIPESTATUS[0]}` = cmd1's exit, `[1]` = cmd2's, `[2]` = cmd3's. Useful with `set -e` and `set -o pipefail` to catch mid-pipeline failures.",
    },
  ],

  "mixed-4": [
    // ── Later topics (08-10) ─────────────────────────────────────
    {
      q: "What does `bash -x script.sh` do?",
      options: ["Checks syntax only", "Runs the script with xtrace — prints each command before executing (same as `set -x` inside)", "Runs as a different user", "Makes the script executable first"],
      answer: 1,
      explain: "`-x` on the command line is handy for debugging scripts you can't modify. You see each expanded command prefixed with `+`. Combine with `-e` for early exit on errors.",
    },
    {
      q: "What does `journalctl -b` show?",
      options: ["Boot device logs", "All journal logs from the current boot", "Boot performance logs", "Logs before the last boot"],
      answer: 1,
      explain: "`-b` = current boot. `-b -1` = previous boot. `-b 0` = same as `-b`. Useful after a crash: `journalctl -b -1 -p err` shows errors from the previous (crashed) boot.",
    },
    {
      q: "In bash, what does `2>/dev/null` at the end of a command do?",
      options: ["Redirects stdout to null", "Silences all error messages (stderr) from the command", "Redirects both streams", "Redirects file descriptor 2 to a file"],
      answer: 1,
      explain: "File descriptor 2 = stderr. `2>/dev/null` discards error messages. `>/dev/null 2>&1` discards BOTH stdout and stderr. `2>&1 | tee error.log` captures stderr to a file.",
    },
    {
      q: "What does `while IFS=: read -r user _ uid _ _ home shell; do` do when reading /etc/passwd?",
      options: ["Reads only the first field", "Destructures each line into named variables using `:` as delimiter", "Reads colon characters only", "Reads colons from stdin"],
      answer: 1,
      explain: "`IFS=:` makes `read` split on colons. Each field name maps to a `/etc/passwd` column. `_` is a convention for 'ignore this field'. Elegant way to parse structured text files.",
    },
    {
      q: "What does `ssh-keyscan -H host >> ~/.ssh/known_hosts` do?",
      options: ["Tests SSH connection", "Retrieves and adds host's public key to known_hosts (avoiding the interactive prompt)", "Scans host for open ports", "Generates a new host key"],
      answer: 1,
      explain: "`ssh-keyscan` fetches the host key without connecting. `-H` hashes the hostname. Used in automation where you need to pre-populate `known_hosts` without interactive prompts.",
    },
    {
      q: "What does `set -o pipefail` do in a bash script?",
      options: ["Enables pipe redirection", "Makes a pipeline return failure if ANY command in the pipe fails (not just the last one)", "Shows pipe I/O stats", "Disables pipes"],
      answer: 1,
      explain: "Without `pipefail`, `failing_cmd | true` returns 0 (success) because `true` succeeds. With `pipefail`, the pipeline returns the last non-zero exit code. Essential with `set -e`.",
    },
    {
      q: "What does `htop` show that `top` doesn't by default?",
      options: ["More processes", "Per-CPU-core usage bars, colour coding, mouse support, and easier process killing", "Disk I/O per process", "Network usage"],
      answer: 1,
      explain: "`htop` is an improved interactive process viewer. Shows each CPU core's load as a visual bar, colour-highlights different process states, and lets you scroll and click on processes.",
    },
    {
      q: "What does `nmap -p 1-1024 192.168.1.1` do?",
      options: ["Configures 1024 ports", "Scans the first 1024 TCP ports on 192.168.1.1 to find which are open", "Blocks ports 1-1024", "Lists processes on 1024 ports"],
      answer: 1,
      explain: "`nmap` (network mapper) is a port scanner. `-p 1-1024` scans the 'well-known' port range. `nmap -sV` also tries to identify service versions. Use only on networks you own or are authorised to test.",
    },
    {
      q: "What does `${ARRAY[@]}` expand to in bash?",
      options: ["The first element", "All elements of the array, each as a separate word", "The array's length", "A string of all elements joined"],
      answer: 1,
      explain: "`${ARRAY[@]}` expands each element as a separate word — safe with spaces in elements. `${ARRAY[*]}` joins all with the first character of IFS. Always quote: `\"${ARRAY[@]}\"`.",
    },
    {
      q: "What does `iotop` show?",
      options: ["I/O on TCP sockets", "Per-process disk read/write rates in real-time", "Network I/O", "Open I/O file descriptors"],
      answer: 1,
      explain: "`iotop` is like `top` but for disk I/O. Shows which processes are doing the most reading/writing. Useful for diagnosing slow systems where high `wa%` appears in `top`.",
    },
    {
      q: "What does `chmod 700 ~/.ssh/` do and why is it needed?",
      options: ["Makes ~/.ssh/ hidden", "Restricts ~/.ssh/ to owner-only access — SSH refuses to use keys if the .ssh directory is world-readable", "Sets a special SSH mode", "Backs up the directory"],
      answer: 1,
      explain: "SSH is strict about directory permissions. If `~/.ssh/` is readable by others, SSH may refuse to use your keys. `chmod 700 ~/.ssh/` and `chmod 600 ~/.ssh/authorized_keys` are both required.",
    },
    {
      q: "In bash, what does `${#ARRAY[@]}` return?",
      options: ["The hash of the array", "The number of elements in the array", "The size in bytes", "The length of the first element"],
      answer: 1,
      explain: "`${#ARRAY[@]}` = array length (element count). `${#ARRAY[0]}` = length of the first element (string length). `${#VAR}` = length of a scalar variable.",
    },
    {
      q: "What does `ss -o state established` show?",
      options: ["All sockets", "Only TCP connections currently in the ESTABLISHED state", "Sockets with errors", "Stateful firewall rules"],
      answer: 1,
      explain: "The `state` filter in `ss` selects by TCP state. ESTABLISHED = active connections. Other states: LISTEN, TIME-WAIT, CLOSE-WAIT, SYN-SENT. Useful for checking active connections.",
    },
    {
      q: "What does `printf '%s\\n' \"${ARRAY[@]}\"` do?",
      options: ["Prints array length", "Prints each array element on its own line, safely handling spaces and special characters", "Prints the array name", "Joins array elements"],
      answer: 1,
      explain: "This is the safe way to print array elements one per line. `echo ${ARRAY[@]}` works for simple cases but fails if elements contain newlines. `printf '%s\\n'` handles any content.",
    },
    {
      q: "What does `sudo fail2ban-client status sshd` show?",
      options: ["SSH server status", "Fail2ban's statistics for the sshd jail: currently banned IPs, total bans, filter hits", "Failed SSH connections", "Firewall rules for SSH"],
      answer: 1,
      explain: "Fail2ban protects services by banning IPs that fail authentication too many times. `fail2ban-client status` lists all active jails. `status sshd` shows SSH-specific ban statistics.",
    },
    {
      q: "What does `awk 'NR%2==0' file.txt` print?",
      options: ["Even-numbered lines (2nd, 4th, 6th...)", "Lines where NR is divisible by 2", "Odd-numbered lines", "Line number 2 only"],
      answer: 0,
      explain: "`NR` = current record (line) number. `NR%2==0` is true for even line numbers. No `{print}` needed — the default action when a condition is true is to print the line.",
    },
    {
      q: "What does `sudo sysctl -w net.ipv4.ip_forward=1` do?",
      options: ["Forwards IP packets from version 4 to 6", "Enables IP forwarding — allows the system to route packets between network interfaces", "Resets network settings", "Enables IPv4"],
      answer: 1,
      explain: "IP forwarding is needed for routers, NAT gateways, VPN servers. `-w` = write (apply immediately). Make it permanent by adding `net.ipv4.ip_forward=1` to `/etc/sysctl.conf`.",
    },
    {
      q: "What does `journalctl -u ssh --since '1 hour ago' | grep 'Invalid user'` do?",
      options: ["Shows all SSH logs", "Finds SSH login attempts with non-existent usernames from the last hour", "Removes invalid users from SSH", "Blocks invalid SSH users"],
      answer: 1,
      explain: "Combining journalctl filtering with grep is a quick way to investigate active brute-force attempts. `Invalid user foo from 1.2.3.4` messages are attackers trying random usernames.",
    },
    {
      q: "What does `declare -A MAP` do in bash?",
      options: ["Declares a regular array", "Declares an associative array (hash map) where keys can be strings", "Maps variables to disk", "Declares a read-only array"],
      answer: 1,
      explain: "Associative arrays (bash 4+): `MAP[key]=value`. Access: `${MAP[key]}`. List keys: `${!MAP[@]}`. List values: `${MAP[@]}`. Count: `${#MAP[@]}`. E.g. `MAP[name]='jahid'; MAP[role]='admin'`.",
    },
    {
      q: "What does `ssh -o StrictHostKeyChecking=no user@host` do?",
      options: ["Enforces strict checking", "Disables the 'Are you sure you want to continue connecting?' prompt — adds key automatically", "Only connects to known hosts", "Skips authentication"],
      answer: 1,
      explain: "Useful in automation where you can't respond to prompts. Security note: this skips host key verification, making you vulnerable to MITM attacks. Only use in controlled environments where you trust the network.",
    },
    {
      q: "What does `perf stat ./myprogram` do?",
      options: ["Shows program statistics from last run", "Runs myprogram and reports performance counters: CPU cycles, instructions, cache misses, etc.", "Profiles memory usage", "Sets program CPU priority"],
      answer: 1,
      explain: "`perf` is a powerful Linux profiling tool. `perf stat` shows hardware performance counters. `perf record && perf report` gives CPU profiling. Useful for identifying hot spots in programs.",
    },
    {
      q: "What does `${VAR/old/new}` do in bash?",
      options: ["Divides VAR", "Replaces the FIRST occurrence of 'old' with 'new' in VAR's value", "Replaces all occurrences", "Errors if 'old' is not found"],
      answer: 1,
      explain: "`${VAR/old/new}` = replace first match. `${VAR//old/new}` = replace ALL. `${VAR/#old/new}` = only if at start. `${VAR/%old/new}` = only if at end. No subprocess needed.",
    },
    {
      q: "What does `ss --summary` show?",
      options: ["A summary of failed connections", "Statistics summary: total sockets by type, TCP states", "Summary of listening services", "Package socket statistics"],
      answer: 1,
      explain: "`ss -s` or `ss --summary` gives a compact overview of all socket statistics — how many TCP, UDP, raw sockets and their current state counts. Quick health check for network activity.",
    },
    {
      q: "What does `find /etc -newer /etc/passwd -type f` find?",
      options: ["Files older than /etc/passwd", "Regular files in /etc that were modified more recently than /etc/passwd", "Files named passwd", "Encrypted files"],
      answer: 1,
      explain: "`-newer file` tests if the found item's mtime is more recent than `file`. Useful post-incident: if you know the attack time, use a reference file modified at that time.",
    },
    {
      q: "What does `readonly -f funcname` do in bash?",
      options: ["Creates a read-only file", "Makes the function read-only — it cannot be redefined or unset", "Returns the function definition", "Marks the function as final"],
      answer: 1,
      explain: "`readonly -f` (or `declare -rf`) prevents a function from being overridden. Useful in security contexts or when writing library functions that must not be accidentally redefined.",
    },
    {
      q: "What does `auditctl -w /etc/passwd -p wa` do?",
      options: ["Watches /etc/passwd for read access", "Sets an audit rule to log all writes and attribute changes to /etc/passwd", "Deletes the audit for /etc/passwd", "Backs up /etc/passwd"],
      answer: 1,
      explain: "The Linux Audit system can log file access events. `-w` = watch path, `-p wa` = watch for writes (`w`) and attribute changes (`a`). View events with `ausearch -f /etc/passwd`.",
    },
    {
      q: "What does `ssh -J jumphost user@target` do?",
      options: ["Connects to jumphost", "SSH to target via jumphost as a single command (ProxyJump) without two separate sessions", "Jumps to a job", "Uses jumphost as a DNS resolver"],
      answer: 1,
      explain: "`-J` = ProxyJump. Modern replacement for `-o ProxyCommand=...`. Opens an SSH connection through jumphost to reach target. Can chain multiple jumps: `-J host1,host2`.",
    },
    {
      q: "What does `mapfile -t -d $'\\0' FILES < <(find . -name '*.txt' -print0)` do?",
      options: ["Creates a file named FILES", "Safely reads null-delimited find output into an array — handles filenames with spaces and newlines", "Lists files with 0 bytes", "Deletes .txt files"],
      answer: 1,
      explain: "`-print0` separates filenames with null bytes. `mapfile -d $'\\0'` splits on null bytes. Together they handle ANY filename, including those with spaces, newlines, or special characters.",
    },
    {
      q: "What does `sudo aide --check` do?",
      options: ["Checks for aide updates", "Compares the current filesystem state against the AIDE database — detecting unauthorised file changes", "Checks disk integrity", "Shows aide configuration"],
      answer: 1,
      explain: "AIDE (Advanced Intrusion Detection Environment) creates a cryptographic hash database of files. Running `--check` alerts you to any files that have changed since the baseline was taken.",
    },
    {
      q: "What does `ssh-agent bash` do?",
      options: ["Starts bash without SSH", "Starts a new bash shell with an SSH agent running in it — you can then `ssh-add` keys", "Runs bash on an SSH server", "Tests SSH from bash"],
      answer: 1,
      explain: "`ssh-agent bash` starts an agent and opens a child shell with `SSH_AUTH_SOCK` and `SSH_AGENT_PID` already set. All SSH commands in that shell can use the agent.",
    },
    {
      q: "What does `awk 'BEGIN{FS=\":\"; OFS=\",\"} {print $1,$3}' /etc/passwd` do?",
      options: ["Reads CSV and prints", "Prints username and UID from /etc/passwd as comma-separated pairs", "Converts /etc/passwd to CSV format completely", "Prints first and third columns without delimiter"],
      answer: 1,
      explain: "`BEGIN` block runs before processing. `FS=\":\"` = input field separator. `OFS=\",\"` = output separator. `$1` = username, `$3` = UID. Result: `root,0`, `jahid,1000`, etc.",
    },
    {
      q: "What does `ssh -o ConnectTimeout=5 user@host` do?",
      options: ["Limits session to 5 minutes", "Abandons the connection attempt if it can't connect within 5 seconds", "Sets keepalive to 5 seconds", "Waits 5 seconds before connecting"],
      answer: 1,
      explain: "Without a timeout, SSH can hang for a long time on unreachable hosts. `ConnectTimeout=5` makes scripts fail fast. Also settable in `~/.ssh/config` per-host.",
    },
  ],

  "mixed-5": [
    // ── Later topics (08-10) ─────────────────────────────────────
    {
      q: "What does `systemd-analyze blame` show?",
      options: ["Services that caused errors at boot", "Each service's startup time, sorted to show which ones slow down boot the most", "Services with failed dependencies", "CPU blame for each service"],
      answer: 1,
      explain: "`systemd-analyze blame` identifies boot time culprits. `systemd-analyze critical-chain` shows the critical path. `systemd-analyze plot > boot.svg` generates a visual timeline.",
    },
    {
      q: "What does `bash -c 'echo hello'` do?",
      options: ["Creates a file called 'echo hello'", "Runs the string 'echo hello' as a bash command, useful for running shell commands from non-shell contexts", "Opens bash then types 'echo hello'", "Checks bash config"],
      answer: 1,
      explain: "`-c string` makes bash read commands from the string instead of stdin. Used in `ssh host 'cmd'`, `sudo bash -c '...'`, `xargs bash -c '...'`, and scripting.",
    },
    {
      q: "What does `perf top` do?",
      options: ["Shows top system performance", "Shows a live view of which functions are consuming the most CPU time (like top, but at the function level)", "Profiles the top process only", "Shows performance events in the journal"],
      answer: 1,
      explain: "`perf top` samples the CPU's instruction pointer and shows which kernel or userspace functions are hottest. No need to recompile — works on running programs.",
    },
    {
      q: "What does `sudo journalctl --rotate && sudo journalctl --vacuum-time=7d` do?",
      options: ["Backs up journals", "Rotates journal files and then deletes journal entries older than 7 days", "Compresses journals", "Resets journal to 7-day cycle"],
      answer: 1,
      explain: "`--rotate` forces journal log rotation (creates new active journal). `--vacuum-time=7d` then removes old rotated journals older than 7 days. Combined, they implement a 7-day retention policy.",
    },
    {
      q: "What does `${VAR,,}` do in bash (double comma)?",
      options: ["Removes commas from VAR", "Converts VAR's value to all lowercase", "Strips trailing commas", "Splits VAR on commas"],
      answer: 1,
      explain: "Case modification operators (bash 4+): `^^` = ALL UPPER, `,,` = all lower, `^` = first char upper, `,` = first char lower. `echo ${NAME,,}` lowercases the name.",
    },
    {
      q: "What does `sudo ss -tp state established 'dport = :443'` show?",
      options: ["All HTTPS listeners", "All established connections where the destination port is 443 (HTTPS), with process info", "Connections to port 443 that failed", "Process using TLS"],
      answer: 1,
      explain: "`ss` filter expressions can combine state and port filters. `dport` = destination port, `sport` = source port. This shows which processes have active HTTPS connections open.",
    },
    {
      q: "What does `sudo auditd -s enable` do?",
      options: ["Enables sudo auditing", "Enables the kernel audit subsystem (allows audit rules to take effect)", "Starts the auditd daemon", "Enables SSH audit logging"],
      answer: 1,
      explain: "The kernel audit subsystem must be enabled for `auditctl` rules to work. `auditctl -e 1` enables it. `auditctl -e 0` disables. `auditctl -l` lists current rules.",
    },
    {
      q: "What does `compgen -c | grep ssh` do in bash?",
      options: ["Runs ssh with completion", "Lists all available commands containing 'ssh'", "Compresses ssh commands", "Shows ssh completions only"],
      answer: 1,
      explain: "`compgen -c` generates all executable commands in PATH. Piping to grep filters for SSH-related tools: `ssh`, `ssh-keygen`, `ssh-agent`, `ssh-copy-id`, `sshd`, etc.",
    },
    {
      q: "What does `sudo ip link set eth0 promisc on` do?",
      options: ["Sets a static IP", "Puts the network interface in promiscuous mode — captures all traffic, not just traffic addressed to the host", "Enables the link", "Sets MTU to 1500"],
      answer: 1,
      explain: "Promiscuous mode is required for packet sniffers (tcpdump, Wireshark) to see all traffic on the network segment. On modern switched networks, you only see your own traffic without special network port mirroring.",
    },
    {
      q: "What does `type -a ssh` show?",
      options: ["SSH authentication methods", "All locations of 'ssh' in PATH — reveals if there are multiple versions or aliases", "SSH type (TCP/UDP)", "SSH key types"],
      answer: 1,
      explain: "`type -a` shows all matches for a command name in order: aliases first, then shell functions, then executables in PATH order. Useful for finding shadowed commands.",
    },
    {
      q: "What does `sudo loginctl list-sessions` show?",
      options: ["History of logins", "Currently active login sessions managed by systemd-logind", "Failed login attempts", "Session file list"],
      answer: 1,
      explain: "`loginctl` manages user sessions. `list-sessions` shows active sessions with session ID, UID, user, seat, and TTY. `loginctl terminate-session ID` forcefully ends a session.",
    },
    {
      q: "What does `exec bash` do when run inside a bash script?",
      options: ["Opens a new terminal", "Replaces the current process with a new bash shell — the original script process is gone", "Executes bash script", "Runs bash in exec mode"],
      answer: 1,
      explain: "`exec` replaces the current process with the given command. No fork — the PID stays the same but the program changes. `exec bash` at the end of a script 'becomes' an interactive bash shell.",
    },
    {
      q: "What does `sudo systemctl edit nginx` do?",
      options: ["Opens nginx.conf for editing", "Creates a drop-in override file for the nginx unit that survives package updates", "Edits the nginx binary", "Shows the nginx unit file"],
      answer: 1,
      explain: "`systemctl edit` opens or creates `/etc/systemd/system/nginx.service.d/override.conf`. Overrides are safer than editing the main unit file — they survive nginx package updates. `systemctl edit --full` edits the full unit.",
    },
    {
      q: "What does `awk '{sum += $1} END {print sum}' numbers.txt` do?",
      options: ["Prints each number prefixed with sum", "Sums all values in the first column and prints the total after processing all lines", "Prints the last line", "Counts lines"],
      answer: 1,
      explain: "`END` block runs after all lines are processed. Variables accumulate across lines. `sum += $1` adds the first field of each line. A common awk pattern for aggregation.",
    },
    {
      q: "What does `PasswordAuthentication no` in sshd_config do?",
      options: ["Disables PAM authentication", "Disables password-based SSH login — only key-based auth works", "Removes passwords for all users", "Makes all accounts require keys"],
      answer: 1,
      explain: "The single most impactful SSH hardening step. After setting up key-based auth, disable passwords to make brute-force attacks useless. `sudo systemctl reload sshd` to apply.",
    },
    {
      q: "What does `sudo lynis audit system` do?",
      options: ["Lists system auditors", "Runs a security hardening assessment of the entire system and generates a report with recommendations", "Audits the lynis package", "Checks system logs for lynis"],
      answer: 1,
      explain: "Lynis is a security auditing tool. It checks hundreds of security aspects: open ports, file permissions, PAM config, SSH settings, kernel parameters, installed software, etc. Essential for security baseline checks.",
    },
    {
      q: "What does `nohup command &` achieve that `command &` alone does not?",
      options: ["Runs command faster", "Makes command immune to SIGHUP so it keeps running after you log out", "Runs command in the background with higher priority", "Captures command output"],
      answer: 1,
      explain: "`command &` runs in background but dies when you log out (shell sends SIGHUP). `nohup` makes it ignore SIGHUP. Output goes to `nohup.out` by default. Use `disown` as an alternative.",
    },
    {
      q: "What does `sudo timedatectl set-timezone Europe/Berlin` do?",
      options: ["Sets the hardware clock", "Changes the system timezone to Europe/Berlin", "Configures NTP server", "Sets the locale"],
      answer: 1,
      explain: "`timedatectl` manages system time, date, and NTP sync. `set-timezone` updates `/etc/localtime` (a symlink). `timedatectl status` shows current time, timezone, and NTP status.",
    },
    {
      q: "What does `sudo ss -lntp | awk 'NR>1 {print $4}' | cut -d: -f2 | sort -n` show?",
      options: ["All processes", "A sorted list of port numbers currently being listened on", "All TCP addresses", "Connected ports"],
      answer: 1,
      explain: "A pipeline combining: `ss -lntp` (listening ports), `awk` (skip header, print address field), `cut` (extract port after `:`), `sort -n` (numeric sort). Shows all ports in use at a glance.",
    },
    {
      q: "What does `sudo hostnamectl set-hostname server01` do?",
      options: ["Changes hostname temporarily", "Permanently changes the system's hostname (updates multiple places including /etc/hostname)", "Sets a hostname for SSH only", "Renames the network interface"],
      answer: 1,
      explain: "`hostnamectl` (systemd) updates the static, transient, and pretty hostnames atomically. No reboot needed. Changes appear in new shells immediately via `hostname` command.",
    },
    {
      q: "What does `sudo apt-mark hold nginx` do?",
      options: ["Holds nginx download", "Prevents nginx from being upgraded or removed by apt", "Pauses the nginx service", "Marks nginx as manually installed"],
      answer: 1,
      explain: "`apt-mark hold` freezes a package at its current version. `apt upgrade` will skip it with a message. Use when a new version has a known regression. `apt-mark unhold nginx` to resume.",
    },
    {
      q: "What does `sudo sshd -t` do?",
      options: ["Tests SSH connection to localhost", "Checks /etc/ssh/sshd_config for syntax errors without restarting sshd", "Times how long sshd takes to start", "Tests the SSH tunnel"],
      answer: 1,
      explain: "`sshd -t` = test mode. Always run this before reloading sshd: `sudo sshd -t && sudo systemctl reload sshd`. A config error could lock you out of the server.",
    },
    {
      q: "What does `watch -d df -h` do?",
      options: ["Watches for file deletions", "Runs `df -h` repeatedly and highlights any values that changed since the last run", "Deletes empty filesystems", "Shows diff between two df runs"],
      answer: 1,
      explain: "`watch -d` (differences) highlights fields that changed between iterations. Helpful for watching disk usage grow in near real-time without manually running `df` repeatedly.",
    },
    {
      q: "What does `sudo swapoff -a && sudo swapon -a` do?",
      options: ["Disables swap permanently", "Disables all swap then re-enables it — effectively clearing swap memory back to disk", "Toggles swap on and off twice", "Resizes swap"],
      answer: 1,
      explain: "This clears swap: moves all swapped-out pages back to RAM (or discards them). Useful after memory pressure has eased and you want to reclaim swap space. Only works if you have enough free RAM.",
    },
    {
      q: "What does `sudo ss -n state time-wait | wc -l` count?",
      options: ["Waiting connections", "The number of TCP sockets in the TIME-WAIT state", "Time-related socket errors", "Connections waiting for timeout"],
      answer: 1,
      explain: "TIME-WAIT sockets linger after connections close (default 2×MSL ≈ 60 seconds) to catch delayed packets. A very high count can indicate a port exhaustion problem on a busy server.",
    },
    {
      q: "What does `sudo systemctl show nginx --property=MainPID` show?",
      options: ["nginx's start time", "The PID of nginx's main process as reported by systemd", "nginx's port number", "Whether nginx is enabled"],
      answer: 1,
      explain: "`systemctl show --property=KEY` extracts a specific property from a unit's status data. Useful in scripts: `PID=$(systemctl show nginx --property=MainPID --value)`.",
    },
    {
      q: "What does `sudo iptables -I INPUT 1 -s 10.0.0.5 -j DROP` do?",
      options: ["Allows 10.0.0.5", "Inserts a rule at position 1 of the INPUT chain to drop all packets from 10.0.0.5", "Logs packets from 10.0.0.5", "Routes 10.0.0.5 to another server"],
      answer: 1,
      explain: "`-I INPUT 1` inserts at position 1 (first rule, highest priority). `-s` = source IP. `-j DROP` = silently discard. Use `-j REJECT` instead to send an error back to the sender.",
    },
    {
      q: "What does `sudo lsof -i -n -P | grep ESTABLISHED | awk '{print $1}' | sort | uniq -c | sort -rn` show?",
      options: ["All open files sorted", "Process names sorted by the number of established network connections, highest first", "Unique network connections", "All network processes"],
      answer: 1,
      explain: "A useful one-liner: `lsof -i` = network files, `-n -P` = no DNS/port lookups. `grep ESTABLISHED` = active connections. `awk '{print $1}'` = process name. `sort | uniq -c | sort -rn` = ranked frequency.",
    },
    {
      q: "What does `sudo systemctl list-timers` show?",
      options: ["NTP synchronisation timers", "All systemd timer units — systemd's alternative to cron — with their next/last trigger times", "System uptime timers", "Process CPU time limits"],
      answer: 1,
      explain: "Systemd timers (`.timer` units) are the modern alternative to cron. They can trigger `.service` units on schedules. `list-timers` shows when each timer last ran and when it will next run.",
    },
    {
      q: "What does `sudo ip netns exec mynamespace ping 8.8.8.8` do?",
      options: ["Creates a network namespace", "Runs ping inside the 'mynamespace' network namespace — its own isolated network stack", "Tests the namespace configuration", "Pings 8.8.8.8 on behalf of a namespace"],
      answer: 1,
      explain: "Network namespaces give processes an isolated network stack (their own interfaces, routing, firewall rules). This is how Docker containers get separate networking. `ip netns list` shows existing namespaces.",
    },
    {
      q: "What does `sudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf(\"%s\\n\", str(args->filename)); }'` do?",
      options: ["Opens a file", "Traces every file-open syscall system-wide in real-time, printing the filename", "Lists open files", "Blocks file access"],
      answer: 1,
      explain: "BPFtrace uses eBPF to attach lightweight programs to kernel tracepoints. This one-liner prints every filename opened by any process — powerful for understanding system behaviour without code changes.",
    },
  ],
};

// Merge extra mixed questions into the main QUESTIONS object
Object.keys(MIXED_EXTRA).forEach(key => {
  if (QUESTIONS[key]) {
    QUESTIONS[key] = QUESTIONS[key].concat(MIXED_EXTRA[key]);
  }
});
