const TOPICS = [
  { id: "01", title: "Introduction to Linux" },
  { id: "02", title: "File System & Navigation" },
  { id: "03", title: "Users & Groups" },
  { id: "04", title: "File Permissions" },
  { id: "05", title: "Package Management" },
  { id: "06", title: "Process Management" },
  { id: "07", title: "Networking" },
  { id: "08-01", title: "Shell Scripting: Basics" },
  { id: "08-02", title: "Shell Scripting: Conditionals" },
  { id: "08-03", title: "Shell Scripting: Loops" },
  { id: "08-04", title: "Shell Scripting: Functions" },
  { id: "09", title: "System Monitoring & Logs" },
  { id: "10", title: "SSH & Remote Access" },
];

const QUESTIONS = {
  "01": [
    {
      q: "What is the Linux kernel?",
      options: [
        "A graphical desktop environment",
        "The core of the OS that manages hardware and resources",
        "A package manager for installing software",
        "A text editor bundled with Linux",
      ],
      answer: 1,
      explain: "The kernel is the core component that sits between hardware and software, managing CPU, memory, and device communication.",
    },
    {
      q: "Which of the following is a Linux distribution?",
      options: ["macOS", "Windows Server", "Ubuntu", "Android"],
      answer: 2,
      explain: "Ubuntu is a Linux distribution. macOS uses Darwin, Windows has its own kernel, and Android uses a modified Linux kernel but is not typically called a 'distro'.",
    },
    {
      q: "What does the command `uname -r` display?",
      options: ["Your username", "The running kernel version", "The root directory contents", "Uptime of the system"],
      answer: 1,
      explain: "`uname -r` prints the running kernel release version, e.g. `6.5.0-41-generic`.",
    },
    {
      q: "In a Linux terminal, what does the `$` at the end of the prompt indicate?",
      options: [
        "You are logged in as root",
        "The command failed",
        "You are logged in as a regular (non-root) user",
        "The shell is waiting for more input",
      ],
      answer: 2,
      explain: "`$` means you are a regular user. `#` means you are root (superuser).",
    },
    {
      q: "Which command prints the current working directory?",
      options: ["ls", "cd", "pwd", "dir"],
      answer: 2,
      explain: "`pwd` (print working directory) outputs the full path of the directory you are currently in.",
    },
    {
      q: "What is the purpose of the shell in Linux?",
      options: [
        "To manage network connections",
        "To provide a graphical interface",
        "To interpret commands and communicate with the kernel",
        "To compile source code",
      ],
      answer: 2,
      explain: "The shell (e.g. bash, zsh) is a command interpreter — it takes your commands, interprets them, and passes instructions to the kernel.",
    },
    {
      q: "Which file contains the Linux manual page for the `ls` command?",
      options: ["You read it with `man ls`", "/etc/ls.conf", "/usr/share/ls.txt", "/bin/ls.man"],
      answer: 0,
      explain: "`man ls` opens the manual page for `ls`. Manual pages are accessed through the `man` command, not by reading files directly.",
    },
    {
      q: "What is a 'distro' in Linux terminology?",
      options: [
        "A type of shell",
        "A Linux kernel patch",
        "A packaged combination of the Linux kernel plus software and tools",
        "A disk partition format",
      ],
      answer: 2,
      explain: "A distribution (distro) bundles the Linux kernel with a package manager, init system, and software to make a complete OS (e.g. Ubuntu, Fedora, Arch).",
    },
    {
      q: "Which command shows the manual/help page for any command?",
      options: ["help", "info", "man", "doc"],
      answer: 2,
      explain: "`man <command>` shows the full manual page. For example, `man ls` shows all options for `ls`.",
    },
    {
      q: "What does CLI stand for?",
      options: ["Core Linux Interface", "Command Line Interface", "Computer Logic Input", "Central Linux Installation"],
      answer: 1,
      explain: "CLI stands for Command Line Interface — the text-based way of interacting with Linux by typing commands.",
    },
  ],

  "02": [
    {
      q: "What is the root of the Linux file system represented by?",
      options: ["~", "/", "C:\\", "/root"],
      answer: 1,
      explain: "`/` is the top-level directory — everything in Linux exists under it. `~` is your home directory, not the filesystem root.",
    },
    {
      q: "Which directory contains user home directories by default?",
      options: ["/root", "/home", "/users", "/var"],
      answer: 1,
      explain: "/home contains the personal directories for regular users (e.g. /home/jahid). /root is the home directory of the root user only.",
    },
    {
      q: "What does `ls -a` show that `ls` alone does not?",
      options: ["File sizes", "Hidden files (those starting with .)", "File permissions", "Only directories"],
      answer: 1,
      explain: "Files starting with `.` are hidden in Linux. `-a` (all) makes `ls` show them alongside regular files.",
    },
    {
      q: "What is the difference between an absolute path and a relative path?",
      options: [
        "Absolute paths use `/` as separator; relative paths use `\\`",
        "Absolute paths start from `/` (root); relative paths start from the current directory",
        "Absolute paths are shorter; relative paths are longer",
        "There is no difference",
      ],
      answer: 1,
      explain: "An absolute path like `/home/jahid/notes.txt` is always the same regardless of where you are. A relative path like `notes.txt` or `../notes.txt` depends on your current location.",
    },
    {
      q: "Which command creates a directory and all missing parent directories in one step?",
      options: ["mkdir mydir", "mkdir -p a/b/c", "touch a/b/c", "mkdirs a/b/c"],
      answer: 1,
      explain: "`mkdir -p a/b/c` creates `a`, then `a/b`, then `a/b/c` — even if none of them exist yet. Without `-p`, `mkdir` fails if the parent doesn't exist.",
    },
    {
      q: "What does `tail -f /var/log/syslog` do?",
      options: [
        "Shows the first 10 lines of the file",
        "Deletes the last 10 lines",
        "Shows new lines as they are added to the file in real-time",
        "Formats the log file",
      ],
      answer: 2,
      explain: "`-f` means 'follow' — the terminal keeps updating live as new lines are written to the file. Press Ctrl+C to stop.",
    },
    {
      q: "Which command searches for the text 'error' inside a file?",
      options: ["find 'error' file.txt", "search error file.txt", "grep 'error' file.txt", "locate error file.txt"],
      answer: 2,
      explain: "`grep` searches file contents for a pattern. `find` searches for files by name/properties. `locate` searches a filename database.",
    },
    {
      q: "What does `cd ..` do?",
      options: ["Goes to the home directory", "Goes up one directory level", "Goes to the root directory", "Lists hidden files"],
      answer: 1,
      explain: "`..` always refers to the parent directory. `cd ..` moves you one level up in the directory tree.",
    },
    {
      q: "Which directory stores system-wide configuration files?",
      options: ["/bin", "/var", "/etc", "/lib"],
      answer: 2,
      explain: "`/etc` contains system-wide configuration files (e.g. `/etc/passwd`, `/etc/ssh/sshd_config`). `/bin` has executables, `/var` has variable data like logs.",
    },
    {
      q: "What does `rm -rf directoryname` do?",
      options: [
        "Renames the directory",
        "Removes the directory and all its contents recursively without prompting",
        "Removes only empty directories",
        "Moves the directory to the trash",
      ],
      answer: 1,
      explain: "`-r` = recursive (delete contents), `-f` = force (no confirmation prompts). This permanently deletes everything — there is no undo.",
    },
  ],

  "03": [
    {
      q: "What UID is always assigned to the root user?",
      options: ["1000", "0", "999", "65534"],
      answer: 1,
      explain: "Root always has UID 0. This is how Linux identifies root — not by the username, but by UID 0.",
    },
    {
      q: "Which file stores user account information (username, UID, home directory, shell)?",
      options: ["/etc/shadow", "/etc/group", "/etc/passwd", "/etc/users"],
      answer: 2,
      explain: "`/etc/passwd` stores username, UID, GID, home directory, and default shell. `/etc/shadow` stores hashed passwords separately with tighter permissions.",
    },
    {
      q: "What is the difference between `adduser` and `useradd`?",
      options: [
        "They are identical",
        "`adduser` is interactive and beginner-friendly; `useradd` is low-level and requires flags for home directory etc.",
        "`useradd` creates users with a password; `adduser` does not",
        "`adduser` only works on Fedora; `useradd` only on Debian",
      ],
      answer: 1,
      explain: "`adduser` is a higher-level script (on Debian/Ubuntu) that prompts you interactively and sets up the home directory automatically. `useradd` is the raw low-level command requiring explicit flags like `-m -s`.",
    },
    {
      q: "What does `usermod -aG developers jahid` do?",
      options: [
        "Removes jahid from the developers group",
        "Creates a new group called developers",
        "Adds jahid to the developers group while keeping existing groups",
        "Sets developers as jahid's primary group",
      ],
      answer: 2,
      explain: "`-a` = append (keep existing groups), `-G` = supplementary group. Without `-a`, using just `-G` would REPLACE all groups with only `developers`.",
    },
    {
      q: "What is the difference between `su -` and `su`?",
      options: [
        "They are identical",
        "`su -` loads the target user's full environment; `su` keeps your current environment",
        "`su -` requires root; `su` does not",
        "`su` is for switching to root only; `su -` can switch to any user",
      ],
      answer: 1,
      explain: "`su -` starts a full login shell — it loads the target user's PATH, environment variables, and runs their login scripts. Plain `su` switches user but keeps the current environment.",
    },
    {
      q: "Which command lets you run a command as root without switching to the root user permanently?",
      options: ["su root -c", "sudo", "runasroot", "exec root"],
      answer: 1,
      explain: "`sudo` (superuser do) runs a single command with elevated privileges, then returns to your normal user session. It also logs what was run.",
    },
    {
      q: "Which file controls which users can use `sudo`?",
      options: ["/etc/sudoers", "/etc/sudo.conf", "/etc/permissions", "/etc/shadow"],
      answer: 0,
      explain: "`/etc/sudoers` defines who can use sudo and with what restrictions. Always edit it with `visudo` — it validates syntax before saving to prevent lock-outs.",
    },
    {
      q: "What command shows all groups a user belongs to?",
      options: ["id username", "groups username", "cat /etc/group", "Both A and B"],
      answer: 3,
      explain: "Both `id jahid` (shows UID, GID, and all groups) and `groups jahid` (shows group names) work. `cat /etc/group` shows all groups on the system.",
    },
    {
      q: "What does `passwd -l jahid` do?",
      options: [
        "Lists jahid's password",
        "Locks jahid's account (disables password login)",
        "Sets a new password for jahid",
        "Deletes jahid's password",
      ],
      answer: 1,
      explain: "`-l` locks the account by prefixing the password hash with `!` in `/etc/shadow`, preventing login. Unlock with `passwd -u`.",
    },
    {
      q: "Which UID range is typically used for regular user accounts on modern Linux?",
      options: ["0–99", "100–499", "500–999", "1000 and above"],
      answer: 3,
      explain: "UIDs 0 is root, 1–999 are reserved for system accounts and daemons. Regular users start at UID 1000 on most modern distributions.",
    },
  ],

  "04": [
    {
      q: "What does the permission string `-rwxr-xr--` mean for the 'others' category?",
      options: ["Read, write, execute", "Read and execute only", "Read only", "No permissions"],
      answer: 2,
      explain: "The last three characters `r--` represent others: read=yes, write=no, execute=no. So others can only read the file.",
    },
    {
      q: "What numeric (octal) value represents `rwxr-xr--`?",
      options: ["764", "754", "744", "774"],
      answer: 1,
      explain: "owner: rwx=4+2+1=7, group: r-x=4+0+1=5, others: r--=4+0+0=4. Combined: 754.",
    },
    {
      q: "What does `chmod +x script.sh` do?",
      options: [
        "Makes the file readable by everyone",
        "Adds execute permission for the owner only",
        "Adds execute permission for owner, group, and others",
        "Removes execute permission",
      ],
      answer: 2,
      explain: "When no category is specified (no `u`, `g`, or `o` prefix), `+x` adds execute for all three: owner, group, and others.",
    },
    {
      q: "What is the SUID (Set User ID) bit used for?",
      options: [
        "Makes a file readable only by its owner",
        "Allows a file to run with the permissions of its owner, not the user running it",
        "Prevents deletion of files in a directory",
        "Sets the default group for files created in a directory",
      ],
      answer: 1,
      explain: "SUID lets users run an executable as if they were the file's owner. Classic example: `/usr/bin/passwd` is SUID root so regular users can change their own password.",
    },
    {
      q: "A directory has the sticky bit set (`drwxrwxrwt`). What does this mean?",
      options: [
        "Only root can delete files in it",
        "Only the file owner (or root) can delete their own files, even if others have write access",
        "All files in the directory are hidden",
        "Files inherit the directory's permissions",
      ],
      answer: 1,
      explain: "The sticky bit on a directory (shown as `t`) means users can only delete files they own, even if the directory is world-writable. This is why `/tmp` uses it.",
    },
    {
      q: "What does `chmod g-w file.txt` do?",
      options: [
        "Removes write permission from the owner",
        "Removes write permission from the group",
        "Removes write permission from others",
        "Removes all write permissions",
      ],
      answer: 1,
      explain: "`g` = group, `-` = remove, `w` = write. This removes write permission from the group while leaving owner and others unchanged.",
    },
    {
      q: "What does `chown jahid:developers file.txt` do?",
      options: [
        "Changes only the owner to jahid",
        "Changes only the group to developers",
        "Changes the owner to jahid AND the group to developers",
        "Adds jahid to the developers group",
      ],
      answer: 2,
      explain: "`chown user:group` changes both owner and group in one command. `chown jahid file.txt` changes owner only; `chown :developers file.txt` changes group only.",
    },
    {
      q: "If `umask` is set to `022`, what permissions will a newly created file have?",
      options: ["777", "755", "644", "600"],
      answer: 2,
      explain: "Files start at 666 (no execute by default). 666 minus umask 022 = 644 (rw-r--r--). Directories start at 777, so 777-022=755.",
    },
    {
      q: "What does the first character in `ls -l` output (e.g. `-`, `d`, `l`) indicate?",
      options: ["The owner's read permission", "The file type", "The number of hard links", "Whether the file is hidden"],
      answer: 1,
      explain: "The first character indicates the file type: `-` = regular file, `d` = directory, `l` = symbolic link, `b` = block device, etc.",
    },
    {
      q: "Which command lets you view and set Access Control Lists (ACLs) for fine-grained permissions?",
      options: ["chmod", "chown", "getfacl / setfacl", "umask"],
      answer: 2,
      explain: "ACLs extend the standard permission model. `getfacl file` shows ACL entries, `setfacl -m u:alice:rw file` grants alice read+write without changing the standard permissions.",
    },
  ],

  "05": [
    {
      q: "Why should you always run `sudo apt update` before `sudo apt install`?",
      options: [
        "To upgrade already-installed packages",
        "To refresh the local package list so apt knows the latest available versions",
        "To check for broken packages",
        "It's not necessary — install works fine without it",
      ],
      answer: 1,
      explain: "`apt update` refreshes the package index from repositories. Without it, apt may try to install old versions or fail to find newly added packages.",
    },
    {
      q: "What is the difference between `apt remove` and `apt purge`?",
      options: [
        "They are identical",
        "`apt remove` removes the package; `apt purge` also removes configuration files",
        "`apt purge` removes the package; `apt remove` only disables it",
        "`apt remove` is for system packages; `apt purge` is for user packages",
      ],
      answer: 1,
      explain: "`apt remove` uninstalls the program but keeps config files (useful if you plan to reinstall). `apt purge` removes everything including config files — a clean uninstall.",
    },
    {
      q: "What does `sudo apt autoremove` do?",
      options: [
        "Automatically updates all packages",
        "Removes packages that were installed as dependencies but are no longer needed",
        "Removes packages that haven't been used in 30 days",
        "Repairs broken package installations",
      ],
      answer: 1,
      explain: "When you uninstall a package, its dependencies may be left behind. `autoremove` cleans up these now-orphaned dependency packages.",
    },
    {
      q: "Which command shows detailed information about a package (description, version, dependencies) WITHOUT installing it?",
      options: ["apt info", "apt show", "dpkg -s", "Both B and C"],
      answer: 3,
      explain: "Both `apt show packagename` and `dpkg -s packagename` show package details. `apt show` works for available packages; `dpkg -s` works for already-installed ones.",
    },
    {
      q: "What does `dpkg -L nginx` do?",
      options: [
        "Lists all packages installed on the system",
        "Lists all files installed by the nginx package",
        "Locks the nginx package to prevent updates",
        "Shows the nginx package log",
      ],
      answer: 1,
      explain: "`dpkg -L <package>` lists every file that was installed as part of that package — useful for finding where config files, binaries, or documentation were placed.",
    },
    {
      q: "A `.deb` file is a:",
      options: [
        "Debian/Ubuntu package file that can be installed with dpkg",
        "Compressed archive like .tar.gz",
        "Shell script installer",
        "Red Hat package format",
      ],
      answer: 0,
      explain: "`.deb` is the package format for Debian/Ubuntu systems. Install with `sudo dpkg -i package.deb` or `sudo apt install ./package.deb`.",
    },
    {
      q: "What is the equivalent of `apt` on Red Hat / Fedora / CentOS systems?",
      options: ["yum / dnf", "rpm only", "snap", "brew"],
      answer: 0,
      explain: "Red Hat-based distros use `yum` (older) or `dnf` (modern). `dnf install nginx` is equivalent to `apt install nginx`. Both use `rpm` packages underneath.",
    },
    {
      q: "Which file lists the repositories that `apt` uses to find packages?",
      options: ["/etc/apt/packages.list", "/etc/apt/sources.list", "/var/apt/repos.conf", "/etc/apt/repos"],
      answer: 1,
      explain: "`/etc/apt/sources.list` (and files in `/etc/apt/sources.list.d/`) contain the URLs of repositories that apt searches when installing packages.",
    },
    {
      q: "What does `sudo apt upgrade` do (as opposed to `apt update`)?",
      options: [
        "Refreshes the package list",
        "Installs a newer version of Ubuntu",
        "Installs available updates for all currently installed packages",
        "Upgrades only security patches",
      ],
      answer: 2,
      explain: "`apt update` = refresh the index (no installations). `apt upgrade` = actually download and install newer versions of all installed packages.",
    },
    {
      q: "Which command tells you which package installed a specific file (e.g. `/usr/bin/curl`)?",
      options: ["apt show curl", "which curl", "dpkg -S /usr/bin/curl", "dpkg -L curl"],
      answer: 2,
      explain: "`dpkg -S <filepath>` does a reverse lookup — given a file path, it tells you which package owns it. Very useful for tracking down where something came from.",
    },
  ],

  "06": [
    {
      q: "What does the `ps aux` command show?",
      options: [
        "Only processes owned by you",
        "A snapshot of all running processes from all users",
        "A live updating list of processes",
        "Only background processes",
      ],
      answer: 1,
      explain: "`ps aux` shows a static snapshot of all processes. `-a` = all users, `-u` = user-oriented format, `-x` = include processes without a terminal.",
    },
    {
      q: "What is the difference between SIGTERM (signal 15) and SIGKILL (signal 9)?",
      options: [
        "SIGTERM is stronger than SIGKILL",
        "SIGTERM asks the process to stop gracefully; SIGKILL forces immediate termination",
        "SIGKILL only works on root processes",
        "They are identical",
      ],
      answer: 1,
      explain: "SIGTERM is a polite request — the process can catch it, save data, and exit cleanly. SIGKILL cannot be caught or ignored — the kernel kills the process immediately.",
    },
    {
      q: "A process is running in the foreground. How do you send it to the background?",
      options: ["Press Ctrl+C then type `bg`", "Press Ctrl+Z to pause it, then type `bg`", "Type `background` in another terminal", "Press Ctrl+B"],
      answer: 1,
      explain: "Ctrl+Z sends SIGSTOP, pausing the process. Then `bg` resumes it in the background. `fg` brings it back to the foreground.",
    },
    {
      q: "What does `systemctl enable nginx` do?",
      options: [
        "Starts nginx immediately",
        "Installs nginx",
        "Configures nginx to start automatically on boot",
        "Restarts nginx",
      ],
      answer: 2,
      explain: "`enable` creates a symlink so systemd starts the service on boot. It does NOT start it immediately. Use `systemctl start nginx` to start it now.",
    },
    {
      q: "What is a zombie process?",
      options: [
        "A process consuming 100% CPU",
        "A process that has finished but whose exit status hasn't been collected by its parent",
        "A process running as root without permission",
        "A process that ignores all signals",
      ],
      answer: 1,
      explain: "A zombie process has finished executing but its entry remains in the process table because the parent hasn't called `wait()` to collect its exit status. It uses no CPU or memory, just a PID.",
    },
    {
      q: "What does `nice -n 10 myscript.sh` do?",
      options: [
        "Runs myscript.sh with lower priority (gives way to other processes)",
        "Runs myscript.sh with higher priority",
        "Runs myscript.sh 10 times",
        "Sets a 10-second timeout on myscript.sh",
      ],
      answer: 0,
      explain: "Nice values range from -20 (highest priority) to +19 (lowest). A nice value of +10 makes the process yield CPU to others — good for background tasks like backups.",
    },
    {
      q: "In crontab, what does the entry `0 2 * * *` mean?",
      options: [
        "Every 2 minutes",
        "At 2:00 AM every day",
        "Every 2 hours",
        "At minute 0, hour 2, on the 2nd of every month",
      ],
      answer: 1,
      explain: "Crontab fields: minute hour day month weekday. `0 2 * * *` = minute 0, hour 2, every day, every month, every weekday = 2:00 AM daily.",
    },
    {
      q: "What command shows the systemd service logs for nginx in real-time?",
      options: ["tail -f /var/log/nginx", "systemctl logs nginx -f", "journalctl -u nginx -f", "logwatch nginx"],
      answer: 2,
      explain: "`journalctl -u nginx -f` follows (-f) the systemd journal for the nginx unit (-u). This works for any systemd service.",
    },
    {
      q: "What does `nohup command &` do?",
      options: [
        "Runs the command with no output",
        "Runs the command in the background and keeps it running even after you log out",
        "Runs the command as root",
        "Prevents the command from using network",
      ],
      answer: 1,
      explain: "`nohup` (no hang up) makes the command ignore the HUP signal sent when you log out. `&` puts it in the background. Together they let a process outlive your session.",
    },
    {
      q: "Which command shows the PID of a process by its name?",
      options: ["pidof / pgrep", "ps -name", "find /proc -name", "top -p name"],
      answer: 0,
      explain: "`pgrep nginx` or `pidof nginx` returns the PID(s) of running processes matching that name. Useful when you need the PID to send a signal.",
    },
  ],

  "07": [
    {
      q: "What does the `-c 4` flag do in `ping -c 4 google.com`?",
      options: [
        "Sets a 4-second timeout",
        "Sends exactly 4 packets then stops",
        "Uses 4 bytes per packet",
        "Repeats the ping 4 times per second",
      ],
      answer: 1,
      explain: "Without `-c`, ping runs forever. `-c 4` (count) sends exactly 4 ICMP packets and then exits.",
    },
    {
      q: "What does `ss -tulnp` show?",
      options: [
        "All active SSH connections",
        "Listening TCP and UDP ports with their associated processes",
        "Network interface statistics",
        "Firewall rules",
      ],
      answer: 1,
      explain: "`-t` = TCP, `-u` = UDP, `-l` = listening, `-n` = numeric (no DNS lookup), `-p` = show process name/PID. This is the standard command to see what's listening on which port.",
    },
    {
      q: "What is the purpose of `/etc/hosts`?",
      options: [
        "Lists all users allowed to connect via SSH",
        "Maps hostnames to IP addresses locally, bypassing DNS",
        "Configures network interfaces",
        "Stores firewall rules",
      ],
      answer: 1,
      explain: "`/etc/hosts` is checked before DNS. If you add `192.168.1.10 myserver` to it, `ping myserver` resolves to that IP without any DNS query.",
    },
    {
      q: "What does `dig google.com A +short` return?",
      options: [
        "The full DNS record including TTL and nameservers",
        "Only the A record IP addresses for google.com",
        "The MX records for google.com",
        "The reverse DNS lookup for google.com",
      ],
      answer: 1,
      explain: "`A` requests the Address record (IPv4). `+short` outputs only the answer — just the IP address(es) without all the extra query metadata.",
    },
    {
      q: "Before enabling UFW with `sudo ufw enable`, what should you always do?",
      options: [
        "Reboot the system",
        "Run `apt update`",
        "Add a rule to allow SSH (`sudo ufw allow ssh`) to avoid being locked out",
        "Disable all network interfaces",
      ],
      answer: 2,
      explain: "If you enable UFW without allowing SSH first, all incoming connections are blocked — including your current SSH session. You'd be locked out of a remote server permanently.",
    },
    {
      q: "What is the difference between `scp` and `rsync`?",
      options: [
        "They are identical",
        "`scp` copies files securely; `rsync` only transfers files that have changed, making repeat syncs faster",
        "`rsync` is encrypted; `scp` is not",
        "`scp` works over SSH; `rsync` works over FTP",
      ],
      answer: 1,
      explain: "Both transfer files over SSH. `rsync` is smarter — it compares source and destination and only transfers differences, making it much faster for repeat syncs of large directories.",
    },
    {
      q: "What does `ip addr show` display?",
      options: [
        "The routing table",
        "All DNS servers",
        "All network interfaces with their IP addresses",
        "Active firewall rules",
      ],
      answer: 2,
      explain: "`ip addr show` lists all network interfaces (eth0, lo, wlan0, etc.) along with their assigned IP addresses, MAC addresses, and state.",
    },
    {
      q: "Which file on a Linux system contains the configured DNS resolver addresses?",
      options: ["/etc/dns.conf", "/etc/resolv.conf", "/etc/network/dns", "/etc/hosts"],
      answer: 1,
      explain: "`/etc/resolv.conf` contains `nameserver` entries pointing to DNS servers (e.g. `nameserver 8.8.8.8`). This is where the system looks when resolving domain names.",
    },
    {
      q: "What does `nc -zv 192.168.1.10 22` test?",
      options: [
        "Connects to port 22 and opens an interactive session",
        "Scans all ports on 192.168.1.10",
        "Tests whether port 22 is open/reachable on 192.168.1.10 without sending data",
        "Sends a file to port 22",
      ],
      answer: 2,
      explain: "`-z` = zero-I/O mode (just test connectivity, send no data), `-v` = verbose. Useful for checking if a service port is reachable before attempting a full connection.",
    },
    {
      q: "What does `traceroute google.com` show?",
      options: [
        "The DNS records for google.com",
        "Each network hop (router) the packet passes through from your machine to google.com",
        "The response time of google.com",
        "The IP address of google.com",
      ],
      answer: 1,
      explain: "`traceroute` shows the path packets take across the network — each line is a router (hop). Useful for diagnosing where a connection is failing or slow.",
    },
  ],

  "08-01": [
    {
      q: "What is the shebang line and where must it appear?",
      options: [
        "A comment line that can appear anywhere in the script",
        "The very first line of the script, starting with `#!`, that tells Linux which interpreter to use",
        "A line that must appear after every function definition",
        "An optional line that improves performance",
      ],
      answer: 1,
      explain: "`#!/bin/bash` must be the very first line (line 1, character 1). It tells the kernel to use `/bin/bash` to execute the script.",
    },
    {
      q: "What is wrong with this variable assignment? `NAME = \"Jahid\"`",
      options: [
        "The quotes are wrong — should be single quotes",
        "Spaces around `=` are not allowed in bash variable assignments",
        "Variable names must be lowercase",
        "Nothing is wrong",
      ],
      answer: 1,
      explain: "Bash has no spaces around `=`. `NAME=\"Jahid\"` is correct. `NAME = \"Jahid\"` makes bash think `NAME` is a command with `=` as an argument.",
    },
    {
      q: "What does `$(date)` do inside a string?",
      options: [
        "Prints the literal text `$(date)`",
        "Runs the `date` command and substitutes its output into the string",
        "Creates a variable called `date`",
        "Causes a syntax error",
      ],
      answer: 1,
      explain: "`$()` is command substitution — it runs the command inside and replaces `$(...)` with the command's output. So `echo \"Today: $(date)\"` prints today's date.",
    },
    {
      q: "What is stored in `$1` inside a shell script?",
      options: [
        "The script's process ID",
        "The exit code of the last command",
        "The first argument passed to the script when it was run",
        "The script's filename",
      ],
      answer: 2,
      explain: "`$1` is the first positional argument. If you run `./greet.sh Alice`, then `$1` = `Alice`. `$0` is the script name, `$$` is the PID, `$?` is the last exit code.",
    },
    {
      q: "Why do you need `./` before a script name when running it (e.g. `./hello.sh`)?",
      options: [
        "It makes the script run faster",
        "Linux does not search the current directory for commands by default; `./` explicitly means 'this directory'",
        "It grants the script root permissions",
        "It is required only when the script has spaces in its name",
      ],
      answer: 1,
      explain: "For security, Linux's PATH doesn't include `.` (current directory). So `hello.sh` would not be found. `./hello.sh` explicitly tells the shell where to find it.",
    },
    {
      q: "What does `$#` hold?",
      options: ["The PID of the script", "The exit code of the last command", "The number of arguments passed to the script", "The script's filename"],
      answer: 2,
      explain: "`$#` is the argument count. If you run `./script.sh a b c`, then `$#` = 3. Useful for validating that the right number of arguments were provided.",
    },
    {
      q: "What does `read -p \"Enter name: \" NAME` do?",
      options: [
        "Reads a file called NAME",
        "Displays 'Enter name: ' as a prompt and stores whatever the user types into the variable NAME",
        "Reads the NAME environment variable",
        "Prints the NAME variable",
      ],
      answer: 1,
      explain: "`read` waits for keyboard input. `-p` shows a prompt text. The typed value is stored in the named variable.",
    },
    {
      q: "What will `echo $((7 % 3))` print?",
      options: ["2", "1", "0", "2.33"],
      answer: 1,
      explain: "`%` is the modulo (remainder) operator. 7 ÷ 3 = 2 remainder 1. So `7 % 3 = 1`. Bash only does integer math — no decimals.",
    },
    {
      q: "What does `read -sp \"Password: \" PASS` do differently from `read -p`?",
      options: [
        "It stores the password in a secure vault",
        "It hides the typed input (silent mode) so it doesn't appear on screen",
        "It encrypts the password automatically",
        "It requires the password to be at least 8 characters",
      ],
      answer: 1,
      explain: "`-s` = silent mode. The terminal doesn't echo characters as you type — like a real password prompt. The value is still stored in `$PASS` as plain text.",
    },
    {
      q: "How do you capture the output of a command into a variable?",
      options: [
        "`VAR = command`",
        "`VAR=$(command)`",
        "`VAR<<command`",
        "`set VAR=command`",
      ],
      answer: 1,
      explain: "`VAR=$(command)` uses command substitution to run the command and store its output. For example: `TODAY=$(date +%Y-%m-%d)` stores the formatted date.",
    },
  ],

  "08-02": [
    {
      q: "What is wrong with `if [$A -gt 10]; then`?",
      options: [
        "Nothing is wrong",
        "The `-gt` operator should be `>`",
        "There must be spaces inside the brackets: `[ $A -gt 10 ]`",
        "The semicolon after `]` is wrong",
      ],
      answer: 2,
      explain: "`[` is actually a command. It requires spaces around its arguments. `[$A -gt 10]` fails because `[$A` is treated as one token.",
    },
    {
      q: "Which operator checks if two numbers are NOT equal?",
      options: ["`!=`", "`-ne`", "`-nq`", "`<>`"],
      answer: 1,
      explain: "For numbers: `-ne` (not equal), `-eq` (equal), `-lt` (less than), `-gt` (greater than). `!=` is for string comparison.",
    },
    {
      q: "What does `[ -f \"$FILE\" ]` test?",
      options: [
        "Whether the variable FILE is not empty",
        "Whether $FILE exists and is a regular file (not a directory or device)",
        "Whether $FILE is executable",
        "Whether $FILE contains text",
      ],
      answer: 1,
      explain: "`-f` = is a regular file. `-d` = is a directory. `-e` = exists (any type). `-x` = is executable. `-s` = is not empty.",
    },
    {
      q: "Why should you always quote string variables in conditions, like `[ \"$NAME\" = \"root\" ]`?",
      options: [
        "Quotes are decorative — they make no difference",
        "If $NAME is empty or contains spaces, an unquoted variable breaks the condition",
        "Single quotes must be used instead of double quotes",
        "Quotes are only needed with the `!=` operator",
      ],
      answer: 1,
      explain: "If `NAME` is empty, `[ $NAME = \"root\" ]` becomes `[ = \"root\" ]` — a syntax error. Quoted: `[ \"\" = \"root\" ]` — works correctly and evaluates to false.",
    },
    {
      q: "What does `elif` mean in a bash if statement?",
      options: [
        "End of the if block (like `fi`)",
        "Else-if: an additional condition checked only when the previous conditions were false",
        "An error handler for the if block",
        "Execute if all other conditions fail (same as `else`)",
      ],
      answer: 1,
      explain: "`elif condition; then` adds another branch. If the `if` condition was false, bash checks the `elif`. You can chain multiple `elif` blocks.",
    },
    {
      q: "What does `[ ! -d \"$DIR\" ]` test?",
      options: [
        "Whether $DIR is a directory",
        "Whether $DIR does NOT exist as a directory",
        "Whether $DIR is not empty",
        "Whether $DIR is deletable",
      ],
      answer: 1,
      explain: "`!` negates the condition. `[ -d \"$DIR\" ]` = is a directory. `[ ! -d \"$DIR\" ]` = is NOT a directory (or doesn't exist).",
    },
    {
      q: "What does `[ -z \"$VAR\" ]` return true for?",
      options: [
        "When $VAR equals zero",
        "When $VAR is an empty string",
        "When $VAR is not set",
        "When $VAR contains the letter z",
      ],
      answer: 1,
      explain: "`-z` tests for zero-length string. It returns true when the variable is empty (`\"\"`). `-n` tests the opposite: true when the string is non-empty.",
    },
    {
      q: "How do you combine two conditions with AND in bash?",
      options: [
        "`[ cond1 AND cond2 ]`",
        "`[ cond1 ] && [ cond2 ]`",
        "`[ cond1 & cond2 ]`",
        "`if cond1 + cond2`",
      ],
      answer: 1,
      explain: "`[ cond1 ] && [ cond2 ]` runs the second test only if the first is true. You can also use `[[ cond1 && cond2 ]]` with double brackets.",
    },
    {
      q: "What marks the end of an if block in bash?",
      options: ["`end`", "`endif`", "`fi`", "`done`"],
      answer: 2,
      explain: "`fi` closes the if block (`fi` is `if` backwards). `done` closes loops. There is no `end` or `endif` in bash.",
    },
    {
      q: "Which operator checks if a file exists AND is readable?",
      options: ["`-e`", "`-f`", "`-r`", "`-x`"],
      answer: 2,
      explain: "`-r file` = file exists and is readable. `-e` = exists (any type). `-f` = is a regular file. `-x` = is executable. `-w` = is writable.",
    },
  ],

  "08-03": [
    {
      q: "What does `{1..5}` generate in bash?",
      options: ["A range object", "The sequence: 1 2 3 4 5", "An array with indices 1 to 5", "A variable called 1..5"],
      answer: 1,
      explain: "`{1..5}` is brace expansion — bash expands it to `1 2 3 4 5` before the loop runs. `{0..10..2}` generates 0 2 4 6 8 10 (step of 2).",
    },
    {
      q: "What happens if you forget to increment the counter in a `while` loop?",
      options: [
        "The loop runs exactly once",
        "The loop runs forever (infinite loop) — press Ctrl+C to stop",
        "Bash automatically increments it",
        "The script exits with an error",
      ],
      answer: 1,
      explain: "A `while` loop checks the condition at the top of every iteration. If the condition never becomes false (because you never change the counter), the loop never stops.",
    },
    {
      q: "What does `continue` do inside a loop?",
      options: [
        "Exits the loop immediately",
        "Exits the entire script",
        "Skips the rest of the current iteration and jumps to the next one",
        "Pauses the loop for 1 second",
      ],
      answer: 2,
      explain: "`continue` skips any remaining commands in the current loop body and goes back to the top to start the next iteration. `break` exits the loop entirely.",
    },
    {
      q: "Which pattern in a `for` loop iterates over all `.log` files in `/var/log/`?",
      options: [
        "`for FILE in /var/log/*.log`",
        "`for FILE in /var/log/`",
        "`for FILE find /var/log -name '*.log'`",
        "`while FILE in /var/log/*.log`",
      ],
      answer: 0,
      explain: "`for FILE in /var/log/*.log` — the shell expands `*.log` to all matching filenames before the loop starts. The loop variable `FILE` holds each path in turn.",
    },
    {
      q: "How do you read a file line-by-line into a variable in a `while` loop?",
      options: [
        "`for LINE in file.txt`",
        "`while read LINE; do ... done < file.txt`",
        "`while LINE in file.txt; do ... done`",
        "`read -l LINE file.txt`",
      ],
      answer: 1,
      explain: "`while read LINE; do ... done < file.txt` feeds the file into the loop via input redirection (`<`). Each iteration `read` picks up the next line.",
    },
    {
      q: "What does `((COUNT++))` do?",
      options: [
        "Prints the value of COUNT",
        "Decrements COUNT by 1",
        "Increments COUNT by 1",
        "Squares COUNT",
      ],
      answer: 2,
      explain: "`((COUNT++))` uses arithmetic context to add 1 to COUNT. Equivalent to `COUNT=$((COUNT + 1))`. `((COUNT--))` decrements.",
    },
    {
      q: "What does `break` do inside a loop?",
      options: [
        "Pauses the loop",
        "Skips the current iteration",
        "Exits the loop entirely and continues with the script after `done`",
        "Restarts the loop from the beginning",
      ],
      answer: 2,
      explain: "`break` immediately exits the innermost loop. Execution continues at the first statement after the loop's `done`.",
    },
    {
      q: "What is the difference between a `while` loop and an `until` loop?",
      options: [
        "`while` runs forever; `until` runs once",
        "`while` loops while the condition is TRUE; `until` loops while the condition is FALSE",
        "They are identical",
        "`until` is only available in zsh, not bash",
      ],
      answer: 1,
      explain: "`while [ condition ]` continues as long as the condition is true. `until [ condition ]` continues as long as the condition is false (stops when it becomes true).",
    },
    {
      q: "What does `${FILE##*.}` extract from a filename like `report.tar.gz`?",
      options: ["The full filename", "The directory path", "The file extension after the last dot (`gz`)", "The filename without extension (`report.tar`)"],
      answer: 2,
      explain: "`##*.` removes everything up to and including the last `.`, leaving just `gz`. `${FILE%.*}` removes from the last `.` onwards, leaving `report.tar`.",
    },
    {
      q: "In a C-style for loop `for ((i=1; i<=5; i++))`, what does the third part `i++` do?",
      options: [
        "It is the loop condition",
        "It is the update expression executed after each iteration",
        "It sets the initial value",
        "It sets the step direction",
      ],
      answer: 1,
      explain: "C-style for loop: `(( init; condition; update ))`. The three parts are: initialise `i=1`, continue while `i<=5`, and after each iteration run `i++`.",
    },
  ],

  "08-04": [
    {
      q: "What does `local` do when used inside a function?",
      options: [
        "Makes the variable accessible everywhere in the script",
        "Restricts the variable to only exist within that function",
        "Makes the variable read-only",
        "Exports the variable to child processes",
      ],
      answer: 1,
      explain: "Without `local`, variables set inside a function change the global variable of the same name. `local` creates a function-scoped copy, preventing side effects.",
    },
    {
      q: "A function uses `echo $result` to return a value. How do you capture it?",
      options: [
        "`VAR = myfunction`",
        "`VAR=$(myfunction)`",
        "`return myfunction VAR`",
        "`myfunction > VAR`",
      ],
      answer: 1,
      explain: "Functions can't directly return strings with `return` (only 0–255 exit codes). The pattern is: `echo` the result inside the function, then `VAR=$(myfunction)` to capture it.",
    },
    {
      q: "What is the conventional meaning of `return 0` in a function?",
      options: ["The function returned nothing", "Success / true", "Failure / false", "The function should be called 0 more times"],
      answer: 1,
      explain: "By UNIX convention: exit/return code 0 = success (true). Any non-zero = failure (false). This is used directly in `if myfunction; then` conditionals.",
    },
    {
      q: "What does `set -e` do at the top of a script?",
      options: [
        "Enables verbose mode (prints each command before running it)",
        "Exits the script immediately if any command returns a non-zero exit code",
        "Treats all variables as integers",
        "Enables extended globbing",
      ],
      answer: 1,
      explain: "Without `set -e`, the script continues running even after a command fails. With it, any failed command causes immediate exit — preventing cascading failures.",
    },
    {
      q: "What does `set -u` protect against?",
      options: [
        "Running scripts as root",
        "Using unset variables — typos like `$USERNME` instead of `$USERNAME`",
        "Infinite loops",
        "Commands that take too long",
      ],
      answer: 1,
      explain: "Without `-u`, using an undefined variable silently expands to empty string. With `-u`, bash treats it as an error and exits — catching typos in variable names.",
    },
    {
      q: "In `set -euo pipefail`, what does `pipefail` add?",
      options: [
        "Makes pipes fail silently",
        "If any command in a pipeline fails, the whole pipeline returns a failure exit code",
        "Disables pipes altogether",
        "Logs all pipe operations",
      ],
      answer: 1,
      explain: "Without `pipefail`, `false | true` has exit code 0 (only the last command matters). With `pipefail`, the pipeline fails if any command in it fails.",
    },
    {
      q: "What does `$1` refer to inside a function?",
      options: [
        "The first argument passed to the script",
        "The first argument passed to the function",
        "Always the number 1",
        "The function's name",
      ],
      answer: 1,
      explain: "Inside a function, `$1`, `$2`, etc. refer to the function's own arguments, not the script's arguments. Each function has its own positional parameters.",
    },
    {
      q: "Why must functions be defined BEFORE they are called in bash?",
      options: [
        "It's just a style convention",
        "Bash reads and executes scripts top-to-bottom — a function must exist before the line that calls it",
        "Functions must be in a separate file",
        "The order doesn't matter in bash",
      ],
      answer: 1,
      explain: "Unlike some languages, bash doesn't do a pre-scan for function definitions. It reads line by line, so calling a function before it's defined results in 'command not found'.",
    },
    {
      q: "What is `>&2` used for?",
      options: [
        "Redirects output to a file called `2`",
        "Sends output to stderr (standard error) instead of stdout",
        "Duplicates output to two terminals",
        "Increases the output buffer size",
      ],
      answer: 1,
      explain: "`>&2` redirects to file descriptor 2 (stderr). Error messages should go to stderr so they can be separated from normal output and so scripts can check for them.",
    },
    {
      q: "What does `command -v curl` do?",
      options: [
        "Runs curl with verbose output",
        "Shows curl's version",
        "Returns 0 (success) if curl is installed and in PATH, non-zero if not",
        "Lists all curl commands",
      ],
      answer: 2,
      explain: "`command -v` is the reliable way to check if a command exists. It returns its path if found (exit 0) or nothing if not found (exit non-zero). Better than `which` for scripting.",
    },
  ],

  "09": [
    {
      q: "Your system has 4 CPU cores. The load average shows `6.2, 4.1, 2.3`. What does this tell you?",
      options: [
        "The system is idle",
        "The system was overloaded in the last minute (6.2 > 4 cores) but is calming down",
        "The system will crash soon",
        "Only 2.3 processes are running",
      ],
      answer: 1,
      explain: "Load average above the core count means processes are queued waiting for CPU. 6.2 on a 4-core system = overloaded recently, but the 5-min (4.1) and 15-min (2.3) trends show it's improving.",
    },
    {
      q: "In `free -h` output, which column should you look at to know if you're actually running low on RAM?",
      options: ["`free`", "`used`", "`available`", "`buff/cache`"],
      answer: 2,
      explain: "`available` is the correct column. Linux uses RAM for disk caching (`buff/cache`) which appears 'used' but can be freed when needed. `available` = free + reclaimable cache.",
    },
    {
      q: "What does `df -h` show when `Use%` reaches 100%?",
      options: [
        "The system slows down slightly",
        "The filesystem is full — new files cannot be created, services may crash",
        "The disk automatically expands",
        "Old files are automatically deleted",
      ],
      answer: 1,
      explain: "At 100% disk usage, the OS cannot write any new data. Logs stop, applications crash, and the system may become unstable. You should alert at 90% and act before it reaches 100%.",
    },
    {
      q: "What does `journalctl -p err` show?",
      options: [
        "Only error-level messages and above (crit, alert, emerg)",
        "All log messages",
        "Only error messages from the last boot",
        "Error messages from nginx only",
      ],
      answer: 0,
      explain: "`-p err` filters by priority. Priorities: debug < info < notice < warning < err < crit < alert < emerg. `-p err` shows err, crit, alert, and emerg — all the serious ones.",
    },
    {
      q: "What does `journalctl -b -1` show?",
      options: [
        "Logs from 1 hour ago",
        "Logs from the previous boot (the one before the current boot)",
        "The first log entry ever",
        "Logs filtered to priority 1",
      ],
      answer: 1,
      explain: "`-b` = boot. `-b 0` = current boot (default). `-b -1` = previous boot. Useful for diagnosing what happened before a crash or reboot.",
    },
    {
      q: "In the `top` CPU line `%Cpu(s): 2.1 us, 0.5 sy, 97.4 id`, what does `id` mean?",
      options: ["Idle — the CPU is doing nothing", "I/O delay", "IRQ handling", "Idle daemon processes"],
      answer: 0,
      explain: "`id` = idle. 97.4% idle means the CPU is free most of the time — a healthy, relaxed system. High `us` (user) or `sy` (system) means the CPU is busy.",
    },
    {
      q: "Which command finds the top 5 largest directories inside `/var`?",
      options: [
        "`ls -lS /var | head -5`",
        "`du -sh /var/*/ | sort -rh | head -5`",
        "`df -h /var | head -5`",
        "`find /var -type d -size +1M | head -5`",
      ],
      answer: 1,
      explain: "`du -sh /var/*/` gets the size of each subdirectory. `sort -rh` sorts largest-first (human-readable). `head -5` shows only the top 5.",
    },
    {
      q: "What does logrotate do?",
      options: [
        "Rotates (backs up) your entire system",
        "Automatically archives and compresses old log files to prevent them from filling the disk",
        "Encrypts log files for security",
        "Uploads logs to a remote server",
      ],
      answer: 1,
      explain: "Logrotate runs on a schedule (usually daily) and rotates log files — keeping a configured number of old compressed copies and creating a fresh empty log file.",
    },
    {
      q: "What does `dmesg -T` show that plain `dmesg` does not?",
      options: [
        "Kernel errors only",
        "Human-readable timestamps instead of seconds-since-boot",
        "Timestamps in UTC timezone",
        "Thermal sensor readings",
      ],
      answer: 1,
      explain: "Plain `dmesg` shows timestamps as seconds since boot (`[12345.678]`). `-T` converts them to human-readable date/time, making it much easier to correlate events.",
    },
    {
      q: "Which log file would you check first if SSH logins to your server seem suspicious?",
      options: ["/var/log/syslog", "/var/log/auth.log", "/var/log/kern.log", "/var/log/dmesg"],
      answer: 1,
      explain: "`/var/log/auth.log` records all authentication events: SSH logins (successful and failed), sudo usage, and su attempts. It's the first place to check for unauthorized access.",
    },
  ],

  "10": [
    {
      q: "What is the difference between the SSH client and the SSH server (sshd)?",
      options: [
        "They are the same program",
        "The client (`ssh`) initiates connections; the server (`sshd`) listens for and accepts incoming connections",
        "The server is installed on your laptop; the client runs on the remote machine",
        "The client requires a key; the server uses passwords only",
      ],
      answer: 1,
      explain: "`ssh` is the client you run to connect to a remote machine. `sshd` (SSH daemon) runs on the remote machine, listens on port 22, and handles incoming connections.",
    },
    {
      q: "Why are SSH key pairs more secure than passwords?",
      options: [
        "Keys are longer than passwords",
        "Keys are never transmitted over the network — only a mathematical proof of possession is sent",
        "Keys can't be copied",
        "Keys expire automatically",
      ],
      answer: 1,
      explain: "With password auth, your password is verified (and potentially intercepted) over the connection. With key auth, the private key never leaves your machine — only a cryptographic signature is sent.",
    },
    {
      q: "After running `ssh-keygen`, which file should you NEVER share with anyone?",
      options: ["~/.ssh/id_ed25519.pub", "~/.ssh/authorized_keys", "~/.ssh/id_ed25519", "~/.ssh/config"],
      answer: 2,
      explain: "`id_ed25519` is the private key. The `.pub` file is meant to be shared (copied to servers). If someone gets your private key, they can impersonate you to any server that has your public key.",
    },
    {
      q: "What does `ssh-copy-id jahid@192.168.1.10` do?",
      options: [
        "Copies the remote server's key to your machine",
        "Copies your public key to the remote server's `~/.ssh/authorized_keys`",
        "Creates a new SSH key pair on the remote server",
        "Backs up the SSH config",
      ],
      answer: 1,
      explain: "`ssh-copy-id` appends your public key to the remote user's `~/.ssh/authorized_keys`. After this, you can log in without a password.",
    },
    {
      q: "Before restarting sshd after editing `/etc/ssh/sshd_config`, what should you always do?",
      options: [
        "Reboot the server",
        "Run `sudo sshd -t` to test the config for syntax errors",
        "Back up the config to a USB drive",
        "Disconnect all current SSH sessions",
      ],
      answer: 1,
      explain: "`sudo sshd -t` (test mode) validates the config file. A syntax error in sshd_config after restart could lock you out of the server permanently — test first.",
    },
    {
      q: "What does `ServerAliveInterval 60` in `~/.ssh/config` do?",
      options: [
        "Reconnects every 60 seconds",
        "Times out idle connections after 60 seconds",
        "Sends a keep-alive packet every 60 seconds to prevent the connection from dropping",
        "Limits sessions to 60 minutes",
      ],
      answer: 2,
      explain: "Idle SSH connections are often dropped by routers or firewalls. `ServerAliveInterval 60` tells your SSH client to send a ping every 60 seconds to keep the connection alive.",
    },
    {
      q: "What is tmux used for in the context of SSH?",
      options: [
        "Encrypting the SSH connection",
        "Multiplexing multiple SSH connections into one",
        "Keeping a terminal session alive on the server even if your SSH connection drops",
        "Monitoring SSH login attempts",
      ],
      answer: 2,
      explain: "If your SSH connection drops, any running process is killed. tmux runs a session on the server side — if you disconnect, the session keeps running. Reconnect and reattach later.",
    },
    {
      q: "What is the difference between `scp` and `rsync -avz`?",
      options: [
        "`scp` is encrypted; `rsync` is not",
        "`rsync` only copies files that have changed; `scp` always copies everything",
        "`scp` supports directories; `rsync` does not",
        "They are functionally identical",
      ],
      answer: 1,
      explain: "Both use SSH for encryption. `rsync` compares source and destination and transfers only changed files — making repeat syncs much faster for large directories.",
    },
    {
      q: "What does setting `PasswordAuthentication no` in sshd_config do?",
      options: [
        "Disables the root user account",
        "Disables password-based SSH login — only key authentication is allowed",
        "Requires a very strong password",
        "Disables authentication entirely",
      ],
      answer: 1,
      explain: "Disabling password auth forces key-based login. This eliminates brute-force password attacks. Only do this AFTER you've confirmed key authentication works.",
    },
    {
      q: "What does `rsync -avzn` do differently from `rsync -avz`?",
      options: [
        "It transfers files in reverse order",
        "It runs a dry run — shows what would be transferred without actually doing it",
        "It skips files larger than a certain size",
        "It compresses files before transferring",
      ],
      answer: 1,
      explain: "`-n` (or `--dry-run`) simulates the transfer and shows what would happen without making any changes. Always useful before a large sync or when using `--delete`.",
    },
  ],
};
